- .prettierrc
- src/components/Modal/Add/index.jsx
- src/components/Toast/index.jsx
- src/hooks/CRUD/useFetch.jsx
- src/lib/nanoid.jsx
- src/pages/Order/Buyer/AddOrUpdate.jsx
- src/pages/Order/Buyer/index.jsx
- src/pages/Order/Info/index.jsx
- src/state/Order/QueryKeys.jsx
- src/state/Order/buyer.jsx
- src/state/index.jsx
- src/state/utils.jsx
- src/util/Schema/index.jsx
- src/util/Schema/utils.jsx
- src/util/nanoid.jsx
> ++Update prettierrc printWidth to 80, remove unused nanoid.jsx file, and update nanoid generation in nanoid.jsx and buyer.jsx

- src/pages/Order/Properties/AddOrUpdate.jsx
- src/pages/Order/Properties/index.jsx
- src/state/Order.jsx
- src/state/QueryKeys.jsx
- src/util/Schema/index.jsx
- src/util/Schema/utils.jsx
i have added order/properties page, and fixed some bug
> Order/Properties 

- src/pages/Order/Info/AddOrUpdate.jsx
- src/pages/Order/Info/index.jsx
- src/state/Order.jsx
- src/state/QueryKeys.jsx
- src/util/Schema/index.jsx
- Merchendiser: Add, Update, delete 
- Info: Add, Delete
> Order/Mercherdiser Order/Info

- src/pages/Order/Info/AddOrUpdate.jsx
This pull request refactors the Order/Info component by removing unnecessary console.log statements. It improves the code readability and removes unnecessary clutter.
> Refactor Order/Info component and remove console.log statements

- src/hooks/CRUD/useFetch.jsx
- src/pages/Order/Details/Entry/Header.jsx
- src/pages/Order/Details/Entry/index.jsx
- src/pages/Order/Details/index.jsx
Tried to add update in Order description
> Tried to add update in Order description

- .gitignore
- .vscode/settings.json
- src/components/Modal/Delete/index.jsx
- src/pages/Order/Details/Entry/index.jsx
In the order details update page
- Added entry delete function
> Order details entry delete

- src/pages/DyeingAndIron/Swatch/index.jsx
- src/pages/LabDip/Info/Entry/Header.jsx
- src/state/Dyeing.jsx
- src/state/QueryKeys.jsx
- src/ui/Others/ReactSelect/index.jsx
features
- can update recipe for dyeing swatches
> Dyeing swatch feature added

- src/pages/LabDip/Log/RMTransferLog/RMAddOrUpdate.jsx
- src/pages/LabDip/Log/RMTransferLog/RMTransferLog.jsx
- src/pages/LabDip/Log/index.jsx
- src/pages/LabDip/RM/AddOrUpdate.jsx
- src/pages/LabDip/RM/index.jsx
- src/pages/Store/Details/MaterialTrx.jsx
- src/routes/Private/DyeingAndIron.jsx
- src/routes/Private/LabDip.jsx
- src/state/Dyeing.jsx
- src/state/LabDip.jsx
- src/state/QueryKeys.jsx
- src/util/Schema/index.jsx
Lab DIp/ RM
Lab Dip/ RM Log
Dyeing/ RM
Dyeing / RM log
> Lab DIp and Dyeing RM

- src/components/Modal/Delete/index.jsx
- src/pages/Common/Coil/Log/SFGTransferLog/SFGAddOrUpdate.jsx
- src/pages/Common/Coil/Log/SFGTransferLog/SFGTransferLog.jsx
- src/pages/Common/Coil/Log/index.jsx
- src/pages/Common/Coil/SFG/EntryToDyeing/index.jsx
- src/pages/Common/Coil/SFG/index.jsx
- src/pages/LabDip/Info/Entry/index.jsx
- src/routes/Private/Common.jsx
- src/state/Common.jsx
- src/state/Dyeing.jsx
- src/state/QueryKeys.jsx
- src/util/Schema/index.jsx
Common coil to dyeing
-add
-update
-delete
and
labdip info entry index page fix
> Common coil to dyeing add/update/delte and labdip info fix

- src/pages/Common/Coil/SFG/EntryToDyeing/index.jsx
- src/pages/Common/Tape/Log/TapeToDyeingLog/TapeToDyeingAddOrUpdate.jsx
- src/pages/Common/Tape/Log/TapeToDyeingLog/TapeToDying.jsx
- src/pages/Common/Tape/Log/index.jsx
- src/pages/Common/Tape/SFG/index.jsx
- src/routes/Private/Common.jsx
- src/state/Common.jsx
Common tape to dyeing 
-add
-update
-delete
> Common tape to dyeing entry/update/delete

- src/hooks/CRUD/useFetch.jsx
- src/hooks/index.jsx
- src/pages/Common/Coil/Log/SFGTransferLog/SFGTransferLog.jsx
- src/pages/Common/Tape/Log/TapeToDyeingLog/TapeToDyeingAddOrUpdate.jsx
- src/pages/Common/Tape/Log/TapeToDyeingLog/TapeToDying.jsx
- src/pages/Common/Tape/Log/index.jsx
- src/pages/DyeingAndIron/Batch/Details/Information.jsx
- src/pages/DyeingAndIron/Batch/Details/Table.jsx
- src/pages/DyeingAndIron/Batch/Details/index.jsx
- src/pages/DyeingAndIron/Batch/Production/Header.jsx
- src/pages/DyeingAndIron/Batch/Production/index.jsx
- src/pages/DyeingAndIron/Batch/index.jsx
- src/routes/Private/DyeingAndIron.jsx
- src/state/Common.jsx
- src/state/QueryKeys.jsx
- src/util/Schema/index.jsx
Batch Production features
- add
- update
- delete
> Batch Production add/update

- src/components/Modal/Proceed/index.jsx
- src/pages/DyeingAndIron/ThreadBatch/Details/Information.jsx
- src/pages/DyeingAndIron/ThreadBatch/Details/Table.jsx
- src/pages/DyeingAndIron/ThreadBatch/Details/index.jsx
- src/pages/DyeingAndIron/ThreadBatch/Entry/Header.jsx
- src/pages/DyeingAndIron/ThreadBatch/Entry/index.jsx
- src/pages/DyeingAndIron/ThreadBatch/Production/Header.jsx
- src/pages/DyeingAndIron/ThreadBatch/Production/index.jsx
- src/pages/DyeingAndIron/ThreadBatch/index.jsx
- src/routes/Private/DyeingAndIron.jsx
- src/state/Dyeing.jsx
- src/state/QueryKeys.jsx
- src/util/Schema/index.jsx
Dyeing thread batch 
-add
-update
> Dyeing thread batch add/update

- src/pages/DyeingAndIron/ThreadBatch/Entry/index.jsx
- src/pages/Vislon/TeethMolding/Production/Production.jsx
- src/pages/Vislon/TeethMolding/Production/Transaction.jsx
- src/pages/Vislon/TeethMolding/Production/index.jsx
- src/routes/Private/Vislon.jsx
- src/state/QueryKeys.jsx
- src/state/Vislon.jsx
- src/util/Schema/index.jsx
Vislon teeth molding product & transfer add
> Vislon teeth molding product & transfer add

- src/pages/Commercial/PI/Details/Information.jsx
- src/pages/Commercial/PI/Details/Table/index.jsx
- src/pages/Commercial/PI/index.jsx
- src/pages/Slider/DieCasting/Transfer/Entry/AgainstOrder.jsx
- src/util/Schema/index.jsx
Slider transfer against order initial entry
> Slider transfer against order initial entry

- src/pages/Slider/Coloring/Production/Production.jsx
- src/pages/Slider/Coloring/Production/Transaction.jsx
- src/pages/Slider/Coloring/Production/index.jsx
- src/pages/Slider/SliderAssembly/Production/Production.jsx
- src/pages/Slider/SliderAssembly/Production/Transaction.jsx
- src/pages/Slider/SliderAssembly/Production/index.jsx
- src/routes/Private/Slider.jsx
- src/state/QueryKeys.jsx
- src/state/Slider.jsx
- src/util/Schema/index.jsx
Slider assembly and coloring production/transaction entry
> Slider assembly and coloring production/transaction entry

- src/pages/Slider/Coloring/Log/ProductionLog/AddOrUpdate.jsx
- src/pages/Slider/Coloring/Log/ProductionLog/index.jsx
- src/pages/Slider/Coloring/Log/TransactionLog/AddOrUpdate.jsx
- src/pages/Slider/Coloring/Log/TransactionLog/index.jsx
- src/pages/Slider/Coloring/Log/index.jsx
- src/pages/Slider/SliderAssembly/Log/ProductionLog/AddOrUpdate.jsx
- src/pages/Slider/SliderAssembly/Log/ProductionLog/index.jsx
- src/pages/Slider/SliderAssembly/Log/TransactionLog/AddOrUpdate.jsx
- src/pages/Slider/SliderAssembly/Log/TransactionLog/index.jsx
- src/pages/Slider/SliderAssembly/Log/index.jsx
- src/pages/Vislon/Finishing/Production/Production.jsx
- src/pages/Vislon/Finishing/Production/Transaction.jsx
- src/pages/Vislon/Finishing/Production/index.jsx
- src/pages/Vislon/TeethMolding/Log/SFGTransferLog/SFGAddOrUpdate.jsx
- src/routes/Private/Slider.jsx
- src/routes/Private/Vislon.jsx
- src/state/QueryKeys.jsx
- src/state/Slider.jsx
Slider assembly & coloring log edit/delete
> Slider assembly & coloring log edit/delete

- src/pages/Metal/Finishing/Log/ProductionLog/SFGAddOrUpdate.jsx
- src/pages/Metal/Finishing/Log/ProductionLog/index.jsx
- src/pages/Metal/Finishing/Log/TransactionLog/SFGAddOrUpdate.jsx
- src/pages/Metal/Finishing/Log/TransactionLog/index.jsx
- src/pages/Metal/Finishing/Log/index.jsx
- src/pages/Metal/Finishing/Production/Production.jsx
- src/pages/Metal/Finishing/Production/Transaction.jsx
- src/pages/Metal/Finishing/Production/index.jsx
- src/pages/Vislon/Finishing/Log/ProductionLog/SFGAddOrUpdate.jsx
- src/pages/Vislon/Finishing/Log/ProductionLog/index.jsx
- src/pages/Vislon/Finishing/Log/TransactionLog/SFGAddOrUpdate.jsx
- src/pages/Vislon/Finishing/Log/TransactionLog/index.jsx
- src/pages/Vislon/Finishing/Log/index.jsx
- src/pages/Vislon/Finishing/Production/Production.jsx
- src/pages/Vislon/Finishing/Production/Transaction.jsx
- src/pages/Vislon/Finishing/Production/index.jsx
- src/routes/Private/Vislon.jsx
- src/state/Metal.jsx
- src/state/QueryKeys.jsx
- src/state/Vislon.jsx
Metal & Vislon finishing prod/trx edit/delete
> Metal & Vislon finishing prod/trx edit/delete

- src/pages/Common/Coil/Log/CoilToDyeing/index.jsx
- src/pages/Order/Details/Entry/Header.jsx
- src/pages/Order/Info/AddOrUpdate.jsx
- src/util/Schema/index.jsx
Order details updated graments wash to multi-select and some other changes
> Order details graments wash to multi-select 

- .env.development
- src/pages/Slider/Coloring/Log/ProductionLog/AddOrUpdate.jsx
- src/pages/Slider/Coloring/Log/TransactionLog/index.jsx
- src/pages/Slider/Coloring/Log/index.jsx
- src/pages/Slider/Coloring/Production/Production.jsx
- src/pages/Slider/Coloring/Production/Transaction.jsx
- src/pages/Slider/Coloring/Production/index.jsx
- src/pages/Slider/SliderAssembly/Log/ProductionLog/AddOrUpdate.jsx
- src/pages/Slider/SliderAssembly/Log/TransactionLog/AddOrUpdate.jsx
- src/pages/Slider/SliderAssembly/Production/Production.jsx
- src/pages/Slider/SliderAssembly/Production/Transaction.jsx
- src/pages/Slider/SliderAssembly/Production/index.jsx
- src/state/QueryKeys.jsx
- src/state/Slider.jsx
slider assembly production:
- prodcution
- transaction
Coloring production:
- produciton
- Transaction (fix required)
> slider assembly & coloring

- src/layouts/Main/index.jsx
- src/pages/DyeingAndIron/Batch/Entry/index.jsx
- src/pages/DyeingAndIron/Batch/Production/index.jsx
- src/pages/DyeingAndIron/ThreadBatch/Entry/index.jsx
- src/pages/DyeingAndIron/Transfer/EntryUpdate/Update.jsx
- src/pages/DyeingAndIron/Transfer/EntryUpdate/index.jsx
- src/pages/DyeingAndIron/Transfer/Index.jsx
initial dyeing transfer update colors multi-select setup
> initial dyeing transfer update colors multi-select setup

- src/pages/Slider/Coloring/Log/TransactionLog/AddOrUpdate.jsx
- src/pages/Slider/Coloring/Log/TransactionLog/index.jsx
- src/pages/Slider/Coloring/Production/Production.jsx
- src/pages/Slider/Coloring/Production/Transaction.jsx
- src/pages/Slider/SliderAssembly/Log/TransactionLog/AddOrUpdate.jsx
- src/pages/Slider/SliderAssembly/Log/TransactionLog/index.jsx
- src/state/Slider.jsx
Slider coloring transaction features:
log
add
edit
delete
> Slider coloring transaction

- src/pages/DyeingAndIron/ThreadBatch/Dyeing.jsx
- src/pages/DyeingAndIron/ThreadBatch/Entry/index.jsx
- src/pages/DyeingAndIron/ThreadBatch/index.jsx
- src/util/Schema/index.jsx
Dyeing thread batch initial entry fix
> Dyeing thread batch initial entry fix

- src/pages/DyeingAndIron/ThreadBatch/Conneing/Entry/Header.jsx
- src/pages/DyeingAndIron/ThreadBatch/Conneing/Entry/index.jsx
- src/util/Schema/index.jsx
Fixed Dyeing thread batch +dyeing schema
> Fixed Dyeing thread batch +dyeing schema

- src/pages/DyeingAndIron/Transfer/EntryUpdate/Update.jsx
- src/pages/DyeingAndIron/Transfer/EntryUpdate/index.jsx
- src/util/Schema/index.jsx
Fixed some dyeing transfer bugs
> Fixed some dyeing transfer bugs

- src/pages/Slider/Coloring/Log/TransactionLog/AddOrUpdate.jsx
- src/pages/Slider/SliderAssembly/Log/ProductionLog/AddOrUpdate.jsx
- src/pages/Slider/SliderAssembly/Log/TransactionLog/AddOrUpdate.jsx
- src/pages/Slider/SliderAssembly/Production/Production.jsx
- src/pages/Slider/SliderAssembly/Production/Transaction.jsx
- src/pages/Slider/SliderAssembly/Production/index.jsx
- src/util/Schema/index.jsx
> Slider bug fixes

- src/pages/LabDip/Info/Entry/index.jsx
- src/util/Schema/index.jsx
> ci: :bug: labdip info fix

- src/pages/Slider/DieCasting/Production/AddOrUpdate.jsx
- src/pages/Slider/DieCasting/Production/Entry/index.jsx
- src/pages/Slider/DieCasting/Production/index.jsx
- src/pages/Slider/DieCasting/Transfer/AgainstOrder.jsx/AddOrUpdate.jsx
- src/pages/Slider/DieCasting/Transfer/AgainstStock/AddOrUpdate.jsx
- src/pages/Slider/DieCasting/Transfer/Entry/Header.jsx
- src/pages/Slider/DieCasting/Transfer/Entry/index.jsx
- src/pages/Slider/SliderAssembly/Log/ProductionLog/AddOrUpdate.jsx
- src/pages/Slider/SliderAssembly/Production/Production.jsx
- src/pages/Slider/SliderAssembly/Production/index.jsx
- src/pages/Slider/SliderAssembly/Stock/AddOrUpdate.jsx
- src/pages/Slider/SliderAssembly/Stock/Production.jsx
- src/pages/Slider/SliderAssembly/Stock/index.jsx
- src/routes/Private/Slider.jsx
- src/state/QueryKeys.jsx
- src/state/Slider.jsx
- src/util/Schema/index.jsx
Slider assembly stock add/edit, diecasting fixes
> Slider assembly stock add/edit, diecasting fixes

- src/pages/Slider/Coloring/Production/Production.jsx
- src/pages/Slider/SliderAssembly/Log/StockProductionLog/AddOrUpdate.jsx
- src/pages/Slider/SliderAssembly/Log/StockProductionLog/index.jsx
- src/pages/Slider/SliderAssembly/Log/StockTransactionLog/AddOrUpdate.jsx
- src/pages/Slider/SliderAssembly/Log/StockTransactionLog/index.jsx
- src/pages/Slider/SliderAssembly/Log/index.jsx
- src/pages/Slider/SliderAssembly/Production/Production.jsx
- src/pages/Slider/SliderAssembly/Stock/Transaction.jsx
- src/pages/Slider/SliderAssembly/Stock/index.jsx
- src/pages/Vislon/TeethMolding/Production/Production.jsx
- src/state/QueryKeys.jsx
- src/state/Slider.jsx
- src/util/Schema/index.jsx
Slider assembly stock,production & transfer add/edit/delete
> Slider assembly stock,production & transfer add/edit/delete

- src/pages/Slider/Coloring/Log/ProductionLog/AddOrUpdate.jsx
- src/pages/Slider/Coloring/Log/ProductionLog/index.jsx
- src/pages/Slider/Coloring/Log/TransactionLog/AddOrUpdate.jsx
- src/pages/Slider/Coloring/Log/TransactionLog/index.jsx
- src/pages/Slider/Coloring/Production/Production.jsx
- src/pages/Slider/Coloring/Production/Transaction.jsx
- src/pages/Slider/Coloring/Production/index.jsx
- src/pages/Slider/Dashboard/Info/index.jsx
- src/pages/Slider/DieCasting/Production/index.jsx
- src/pages/Slider/DieCasting/Stock/index.jsx
- src/pages/Slider/DieCasting/Transfer/AgainstOrder.jsx/AddOrUpdate.jsx
- src/pages/Slider/DieCasting/Transfer/AgainstOrder.jsx/index.jsx
- src/pages/Slider/DieCasting/Transfer/AgainstStock/AddOrUpdate.jsx
- src/pages/Slider/DieCasting/Transfer/AgainstStock/index.jsx
- src/pages/Slider/DieCasting/Transfer/Entry/index.jsx
- src/pages/Slider/SliderAssembly/Log/ProductionLog/AddOrUpdate.jsx
- src/pages/Slider/SliderAssembly/Log/ProductionLog/index.jsx
- src/pages/Slider/SliderAssembly/Log/TransactionLog/AddOrUpdate.jsx
- src/pages/Slider/SliderAssembly/Log/TransactionLog/index.jsx
- src/pages/Slider/SliderAssembly/Production/Production.jsx
- src/pages/Slider/SliderAssembly/Production/Transaction.jsx
- src/pages/Slider/SliderAssembly/Production/index.jsx
- src/pages/Vislon/Finishing/Production/index.jsx
- src/pages/Vislon/TeethMolding/Production/Transaction.jsx
- src/pages/Vislon/TeethMolding/Production/index.jsx
- src/util/Schema/index.jsx
slider diecasting transaction new form validation and new column display in index pages
> slider diecasting transaction new form validation and new column display in index pages

- src/pages/Nylon/MetallicFinishing/Log/TransferLog/AddOrUpdate.jsx
- src/pages/Nylon/MetallicFinishing/Log/TransferProduction/AddOrUpdate.jsx
- src/pages/Nylon/MetallicFinishing/Log/index.jsx
- src/pages/Nylon/MetallicFinishing/Production/Production.jsx
- src/pages/Nylon/MetallicFinishing/Production/Transaction.jsx
- src/pages/Nylon/PlasticFinishing/Log/TransferLog/AddOrUpdate.jsx
- src/pages/Nylon/PlasticFinishing/Log/TransferLog/index.jsx
- src/pages/Nylon/PlasticFinishing/Log/TransferProduction/AddOrUpdate.jsx
- src/pages/Nylon/PlasticFinishing/Log/TransferProduction/index.jsx
- src/pages/Nylon/PlasticFinishing/Production/Production.jsx
- src/pages/Nylon/PlasticFinishing/Production/Transaction.jsx
- src/pages/Vislon/Finishing/Log/ProductionLog/AddOrUpdate.jsx
- src/pages/Vislon/Finishing/Log/ProductionLog/index.jsx
- src/pages/Vislon/Finishing/Log/TransactionLog/AddOrUpdate.jsx
- src/pages/Vislon/Finishing/Log/TransactionLog/index.jsx
- src/pages/Vislon/Finishing/Production/Production.jsx
- src/pages/Vislon/Finishing/Production/Transaction.jsx
- src/pages/Vislon/Finishing/Production/index.jsx
- src/pages/Vislon/TeethMolding/Log/SFGProduction/AddOrUpdate.jsx
- src/pages/Vislon/TeethMolding/Log/SFGProduction/index.jsx
- src/pages/Vislon/TeethMolding/Log/SFGTransfer/AddOrUpdate.jsx
- src/pages/Vislon/TeethMolding/Log/SFGTransfer/index.jsx
- src/pages/Vislon/TeethMolding/Production/Production.jsx
- src/pages/Vislon/TeethMolding/Production/Transaction.jsx
- src/pages/Vislon/TeethMolding/Production/index.jsx
- src/state/Delivery.jsx
- src/state/Nylon.jsx
- src/util/Schema/index.jsx
Vislon teethmolding and finshing bug fix
> Vislon teethmolding and finshing bug fix

- src/pages/Nylon/MetallicFinishing/Log/TransferLog/AddOrUpdate.jsx
- src/pages/Nylon/MetallicFinishing/Log/TransferProduction/AddOrUpdate.jsx
- src/pages/Nylon/MetallicFinishing/Production/Production.jsx
- src/pages/Nylon/MetallicFinishing/Production/index.jsx
- src/pages/Nylon/PlasticFinishing/Log/TransferLog/index.jsx
- src/pages/Nylon/PlasticFinishing/Log/TransferProduction/index.jsx
- src/pages/Nylon/PlasticFinishing/Production/Production.jsx
- src/pages/Nylon/PlasticFinishing/Production/index.jsx
- src/state/Nylon.jsx
Nylon metal and plastic finishing bug fixes
> Nylon metal and plastic finishing bug fixes 

- src/pages/Metal/Finishing/Log/index.jsx
- src/pages/Metal/Finishing/Production/Production.jsx
- src/pages/Metal/Finishing/Production/index.jsx
- src/pages/Metal/TeethColoring/Log/TransferLog/AddOrUpdate.jsx
- src/pages/Metal/TeethColoring/Log/index.jsx
- src/pages/Metal/TeethColoring/Production/Production.jsx
- src/pages/Metal/TeethColoring/Production/Transaction.jsx
- src/pages/Metal/TeethColoring/Production/index.jsx
- src/pages/Metal/TeethMolding/Log/TransferLog/AddOrUpdate.jsx
- src/pages/Metal/TeethMolding/Log/TransferLog/index.jsx
- src/pages/Metal/TeethMolding/Log/TransferProduction/AddOrUpdate.jsx
- src/pages/Metal/TeethMolding/Log/TransferProduction/index.jsx
- src/pages/Metal/TeethMolding/Log/index.jsx
- src/pages/Metal/TeethMolding/Production/index.jsx
- src/pages/Nylon/MetallicFinishing/Log/index.jsx
- src/pages/Nylon/MetallicFinishing/Production/index.jsx
- src/pages/Nylon/PlasticFinishing/Log/index.jsx
- src/pages/Nylon/PlasticFinishing/Production/index.jsx
- src/pages/Vislon/Finishing/Log/index.jsx
- src/pages/Vislon/Finishing/Production/index.jsx
- src/pages/Vislon/TeethMolding/Log/index.jsx
- src/util/Schema/index.jsx
Metal teeth molding, coloring and finishing bug fixes
> Metal teeth molding, coloring and finishing bug fixes

- src/pages/Commercial/LC/Details/Information.jsx
- src/pages/Commercial/LC/Entry/Header.jsx
- src/pages/Commercial/LC/Entry/index.jsx
- src/ui/Core/index.jsx
- src/util/Schema/index.jsx
Commercial LC entry/edit fixed
> Commercial LC entry/edit fixed

- src/pages/DyeingAndIron/ZipperBatch/Entry/index.jsx
- src/pages/LabDip/ZipperSwatch/index.jsx
Dyeing zipper batch bleach and color checking
> Dyeing zipper batch bleach and color checking

- src/pages/Commercial/LC/Entry/index.jsx
- src/pages/LabDip/Info/Entry/index.jsx
- src/pages/LabDip/ThreadSwatch/index.jsx
- src/pages/Order/Details/Entry/index.jsx
- src/pages/Thread/Order/Entry/index.jsx
- src/state/Other.jsx
-Thread/Order and Order/Deatail Bleach Toggle fixed
-Dyeing/Thread Swatch Bleach added
-Commercial LC Update fixed
> fix: :bug: Commercial LC Update fixed

- src/components/Pdf/OrderSheet/index.jsx
- src/components/Pdf/OrderSheet/utils.jsx
- src/pages/Order/Details/ByOrderNumber/index.jsx
- src/pages/Order/Details/_components/Information/Item.jsx
- src/pages/Order/Details/_components/Information/index.jsx
> Zipper order pdf update

- src/pages/Thread/Conneing/Production.jsx
- src/pages/Thread/Conneing/Transaction.jsx
- src/pages/Thread/Conneing/index.jsx
- src/pages/Thread/Log/Production/AddOrUpdate.jsx
- src/pages/Thread/Log/Production/index.jsx
- src/pages/Thread/Log/Transfer/AddOrUpdate.jsx
- src/pages/Thread/Log/Transfer/index.jsx
- src/pages/Thread/Log/index.jsx
- src/pages/Vislon/TeethMolding/Production/index.jsx
- src/routes/Private/Thread.jsx
- src/state/Dyeing.jsx
- src/state/QueryKeys.jsx
- src/state/Thread.jsx
Thread/coning and log add/edit/delete
> Thread/coning and log add/edit/delete

- src/pages/Order/Details/Entry/Header.jsx
- src/util/Schema/index.jsx
Order/Details the entry form fields updated
>  Order/Details the entry form fields updated

- .env.development
- src/pages/Metal/TeethColoring/Log/index.jsx
- src/pages/Metal/TeethColoring/Production/index.jsx
- Added VPS API base URL and image URL 
- Commented out unused code for Transfer and Total Transaction 
- Updated accessorKey for teeth_coloring_prod to finishing_prod in Production page 
- Removed Trx Transaction and Total Transaction columns from Production page
> chore: Update development environment variables

- src/hooks/CRUD/useFetch.jsx
- src/pages/Order/Details/index.jsx
- src/pages/Thread/Challan/Details/Information.jsx
- src/pages/Thread/Challan/Details/Table/index.jsx
- src/pages/Thread/Challan/Details/index.jsx
- src/pages/Thread/Challan/Entry/Header.jsx
- src/pages/Thread/Challan/Entry/index.jsx
- src/pages/Thread/Challan/index.jsx
- src/routes/Private/Thread.jsx
- src/state/QueryKeys.jsx
- src/state/Thread.jsx
- src/util/Schema/index.jsx
Thread/Challan Add/edit/delete initial
> Thread/Challan Add/edit/delete initial

- src/components/Pdf/OrderSheet/index.jsx
- src/components/Pdf/OrderSheet/utils.jsx
- src/pages/DyeingAndIron/ThreadBatch/Conneing/Entry/Header.jsx
- src/pages/DyeingAndIron/ThreadBatch/Conneing/Entry/index.jsx
- src/pages/DyeingAndIron/ThreadBatch/Entry/Header.jsx
- src/pages/DyeingAndIron/ThreadBatch/Entry/index.jsx
- src/pages/DyeingAndIron/ZipperBatch/Production/index.jsx
- src/pages/Order/Details/index.jsx
- src/state/Order.jsx
- src/state/QueryKeys.jsx
fixed Zipper & Threads batch & production, order pdf and access
> fixed Zipper & Threads batch & production, order pdf and access

- src/pages/Report/PIRegister/index.jsx
- src/pages/Slider/SliderAssembly/Log/ProductionLog/AddOrUpdateProd.jsx
- src/pages/Slider/SliderAssembly/Log/ProductionLog/AddOrUpdateStockProd.jsx
- src/pages/Slider/SliderAssembly/Log/ProductionLog/index.jsx
- src/pages/Slider/SliderAssembly/Log/StockTransactionLog/AddOrUpdate.jsx
- src/pages/Slider/SliderAssembly/Log/StockTransactionLog/index.jsx
- src/pages/Slider/SliderAssembly/Log/index.jsx
- src/pages/Slider/SliderAssembly/Stock/Transaction.jsx
- src/pages/Slider/SliderAssembly/Stock/index.jsx
- src/routes/Private/Report.jsx
- src/state/QueryKeys.jsx
- src/state/Report.jsx
- src/util/Schema/index.jsx
ci: :sparkles: Report PI Register & Slider Assembly log product merge
> ci: :sparkles: Report PI Register & Slider Assembly log product merge

- src/components/Pdf/OrderSheet/utils.jsx
- src/pages/Order/Details/ByOrderNumber/index.jsx
- src/pages/Order/Details/Entry/Header.jsx
- src/pages/Order/Details/_components/Information/index.jsx
- src/pages/Report/DailyChallan/index.jsx
- src/routes/private/Report.jsx
> More bug fixes

- src/hooks/CRUD/useFetch.jsx
- src/hooks/index.jsx
- src/pages/Order/Details/Entry/Header.jsx
- src/pages/Order/Details/Entry/index.jsx
- src/ui/Dynamic/DynamicFormSpreadSheet.jsx
- src/util/Schema/index.jsx
added  order/details slider and all order select options
> added  order/details slider and all order select options

- src/pages/Order/Details/Entry/Header.jsx
- src/pages/Order/Details/Entry/index.jsx
- src/pages/Order/Details/_components/Information/Item.jsx
- src/pages/Order/columns.jsx
- src/ui/Core/index.jsx
- src/util/Schema/index.jsx
Order/details entry size and quantity datatype change to double
> Order/details entry size and quantity datatype change to double 

- src/components/Pdf/OrderSheet/index.jsx
- src/components/Pdf/OrderSheet/utils.jsx
- src/pages/Order/Details/Entry/index.jsx
- src/pages/Order/Details/_components/Information/Item.jsx
- src/pages/Order/Details/_components/Table/index.jsx
- src/pages/Order/Details/_components/ViewByStyle/Table.jsx
- src/pages/Order/columns.jsx
Order/details 
- pdf column fix, 
- pdf double sample fix
- order/details index show sample order column
- order/details entry details_entry quantity field change field type from double to integer
> Order/details pdf column fix, double sample fix

- src/pages/Slider/Coloring/Log/ProductionLog/index.jsx
- src/pages/Slider/Coloring/Log/TransactionLog/index.jsx
- src/pages/Slider/DieCasting/Stock/AddOrUpdate.jsx
- src/pages/Slider/DieCasting/Stock/index.jsx
- src/pages/Slider/DieCasting/Transfer/Entry/index.jsx
- src/pages/Thread/Conneing/Production.jsx
- src/pages/Thread/Conneing/Transaction.jsx
- src/ui/Others/LinkWithCopy.jsx
- src/util/Schema/index.jsx
> Slider and Thread bug fixes

- src/pages/Order/Details/_components/Information/Item.jsx
- src/pages/Order/Properties/AddOrUpdate.jsx
- src/pages/Order/columns.jsx
- src/pages/Report/ProductionReportDirector/zipper.jsx
- src/pages/Report/ProductionReportDirector/zipperFalcy.jsx
- src/pages/Report/ZipperProductionStatus/index.jsx
- src/pages/Store/Stock/AddOrUpdate.jsx
- src/util/Schema/index.jsx
Report, Store, Order Sheet bug fixes
> Report, Store, Order Sheet bug fixes

- src/components/Modal/Delete/index.jsx
- src/pages/Commercial/LC/Entry/DynamicProgression.jsx
- src/pages/Commercial/LC/Entry/Header.jsx
- src/pages/Commercial/LC/Entry/index.jsx
- src/pages/Commercial/LC/index.jsx
- src/pages/Commercial/ManualPI/Details/Information.jsx
- src/pages/Commercial/PI/Entry/Header.jsx
- src/pages/Report/LC/index.jsx
- src/state/Other.jsx
- src/state/QueryKeys.jsx
Lc entry delete and some bug fixes
> Lc entry delete and some bug fixes

- src/components/Modal/Delete/index.jsx
- src/pages/Commercial/LC/Entry/index.jsx
- src/pages/Common/Tape/SFG/AddOrUpdate.jsx
- src/pages/Common/Tape/SFG/index.jsx
- src/pages/LabDip/ThreadSwatch/index.jsx
- src/pages/LabDip/ZipperSwatch/index.jsx
- src/pages/Metal/Finishing/Production/index.jsx
- src/pages/Metal/TeethColoring/Production/Production.jsx
- src/pages/Metal/TeethColoring/Production/index.jsx
- src/pages/Metal/TeethMolding/Production/index.jsx
- src/pages/Nylon/MetallicFinishing/Production/index.jsx
- src/pages/Nylon/PlasticFinishing/Production/index.jsx
- src/pages/Slider/DieCasting/Stock/AddOrUpdate.jsx
- src/pages/Slider/DieCasting/Stock/index.jsx
- src/pages/Slider/DieCasting/Transfer/Entry/index.jsx
- src/pages/Store/Log/AgainstOrder/AddOrUpdate.jsx
- src/pages/Store/Log/AgainstOrder/index.jsx
- src/pages/Store/Stock/AgainstOrderTransfer.jsx
- src/pages/Vislon/Finishing/Production/index.jsx
- src/pages/Vislon/TeethMolding/Production/index.jsx
- src/state/Dyeing.jsx
- src/state/Other.jsx
- src/state/QueryKeys.jsx
- src/util/Schema/index.jsx
Slider, Tape-prep, store, lab-dip bug fixes
> Slider, Tape-prep, store, lab-dip bug fixes

- src/pages/Metal/Finishing/Production/Production.jsx
- src/pages/Metal/Finishing/Production/Transaction.jsx
- src/pages/Slider/Coloring/Production/Production.jsx
- src/pages/Slider/Coloring/Production/index.jsx
- src/pages/Slider/DieCasting/Transfer/Entry/index.jsx
- src/pages/Vislon/Finishing/Production/Production.jsx
- src/state/Nylon.jsx
> Fixed slider,metal bugs

- src/pages/Commercial/LC/Details/Information.jsx
- src/pages/Commercial/LC/Entry/DynamicProgression.jsx
- src/pages/Commercial/LC/Entry/DynamicUD.jsx
- src/pages/Commercial/LC/Entry/Header.jsx
- src/pages/Commercial/LC/Entry/index.jsx
- src/pages/Order/Factory/AddOrUpdate.jsx
- src/pages/Order/Merchandiser/AddOrUpdate.jsx
- src/pages/Order/Party/AddOrUpdate.jsx
- src/pages/Order/Party/index.jsx
- src/pages/Slider/DieCasting/Stock/AddOrUpdate.jsx
- src/pages/Slider/DieCasting/Stock/index.jsx
- src/pages/Slider/SliderAssembly/Stock/AddOrUpdate.jsx
- src/pages/Slider/SliderAssembly/Stock/index.jsx
- src/pages/Store/Log/AgainstOrder/AddOrUpdate.jsx
- src/pages/Store/Log/AgainstOrder/index.jsx
- src/pages/Store/Stock/AgainstOrderTransfer.jsx
- src/state/QueryKeys.jsx
- src/util/Schema/index.jsx
Some bug fixes on slider & Commercial/LC new dynamic field added
> Some bug fixes on slider & Commercial/LC new dynamic field added

- src/pages/Slider/Coloring/Log/ProductionLog/AddOrUpdate.jsx
- src/pages/Slider/Coloring/Log/ProductionLog/index.jsx
- src/pages/Slider/Coloring/Log/TransactionLog/AddOrUpdate.jsx
- src/pages/Slider/Coloring/Log/TransactionLog/index.jsx
- src/pages/Slider/Coloring/Production/Production.jsx
- src/pages/Slider/Coloring/Production/Transaction.jsx
- src/pages/Slider/Coloring/Production/index.jsx
- src/pages/Slider/SliderAssembly/Log/ProductionLog/AddOrUpdateProd.jsx
- src/pages/Slider/SliderAssembly/Log/ProductionLog/AddOrUpdateStockProd.jsx
- src/pages/Slider/SliderAssembly/Log/ProductionLog/index.jsx
- src/pages/Slider/SliderAssembly/Log/TransactionLog/AddOrUpdate.jsx
- src/pages/Slider/SliderAssembly/Log/TransactionLog/index.jsx
- src/pages/Slider/SliderAssembly/Production/Transaction.jsx
- src/pages/Slider/SliderAssembly/Production/index.jsx
Slider: assembly and coloring bug fixes
> Slider: assembly and coloring bug fixes

- src/components/Pdf/OrderSheet/index.jsx
- src/components/Pdf/OrderSheet/utils.jsx
- src/pages/Order/Details/Entry/Header.jsx
- src/pages/Order/Details/Entry/index.jsx
- src/pages/Order/Details/_components/Table/index.jsx
> ci: :bug: Order/details pdf tape fixed

- src/components/Pdf/OrderSheet/index.jsx
- src/components/Pdf/OrderSheet/utils.jsx
- src/pages/Commercial/PI/Entry/index.jsx
- src/pages/Metal/Finishing/Production/Production.jsx
- src/pages/Metal/TeethColoring/Log/Production/index.jsx
- src/pages/Metal/TeethColoring/Production/Production.jsx
- src/pages/Metal/TeethMolding/Log/Production/AddOrUpdate.jsx
- src/pages/Metal/TeethMolding/Log/Production/index.jsx
- src/pages/Metal/TeethMolding/Production/Production.jsx
- src/pages/Metal/TeethMolding/Production/index.jsx
- src/pages/Nylon/MetallicFinishing/Log/Production/AddOrUpdate.jsx
- src/pages/Nylon/MetallicFinishing/Log/Production/index.jsx
- src/pages/Nylon/MetallicFinishing/Production/Production.jsx
- src/pages/Nylon/PlasticFinishing/Log/Production/AddOrUpdate.jsx
- src/pages/Nylon/PlasticFinishing/Log/Production/index.jsx
- src/pages/Nylon/PlasticFinishing/Production/Production.jsx
- src/pages/Vislon/Finishing/Log/Production/AddOrUpdate.jsx
- src/pages/Vislon/Finishing/Log/Production/index.jsx
- src/pages/Vislon/Finishing/Production/Production.jsx
- src/pages/Vislon/TeethMolding/Log/Production/AddOrUpdate.jsx
- src/pages/Vislon/TeethMolding/Log/Production/index.jsx
- src/pages/Vislon/TeethMolding/Production/Production.jsx
- src/pages/Vislon/TeethMolding/Production/index.jsx
- src/util/Schema/index.jsx
Order/Details/pdf slider section and commercial pi invalidation
> ci: :bug: Order/Details/pdf slider section and commercial pi invalidation

- src/pages/Order/Details/Entry/Header.jsx
- src/pages/Order/columns.jsx
- src/pages/Report/LC/index.jsx
> order nad report small fixes

- src/pages/Commercial/PI/Entry/index.jsx
- src/pages/Delivery/Challan/Entry/index.jsx
- src/pages/DyeingAndIron/FinishingBatch/Details/Information.jsx
- src/pages/DyeingAndIron/FinishingBatch/Details/Table/index.jsx
- src/pages/DyeingAndIron/FinishingBatch/Details/index.jsx
- src/pages/DyeingAndIron/FinishingBatch/Entry/Header.jsx
- src/pages/DyeingAndIron/FinishingBatch/Entry/columns.jsx
- src/pages/DyeingAndIron/FinishingBatch/Entry/index.jsx
- src/pages/DyeingAndIron/FinishingBatch/index.jsx
- src/pages/Order/Party/index.jsx
- src/pages/Slider/Dashboard/index.jsx
- src/routes/private/DyeingAndIron.jsx
- src/state/Dyeing.jsx
- src/state/Other.jsx
- src/state/QueryKeys.jsx
- src/util/Schema/index.jsx
Finishing create, update, delete
and details
Zipper challan bug  fix
Finishing api fix
> Finishing create, update, delete

- src/pages/DyeingAndIron/FinishingBatch/Entry/index.jsx
- src/pages/Order/Details/Entry/index.jsx
added slider post to finishing batch
> added slider post to finishing batch

- src/pages/DyeingAndIron/FinishingBatch/index.jsx
- src/pages/Slider/Dashboard/index.jsx
- src/pages/Store/Log/Booking/AddOrUpdate.jsx
- src/pages/Store/Log/Booking/AgainstOrderTransfer.jsx
- src/pages/Store/Log/Booking/MaterialTrx.jsx
- src/pages/Store/Log/Booking/index.jsx
- src/pages/Store/Log/PurchaseLog/index.jsx
- src/pages/Store/Log/index.jsx
- src/pages/Store/Stock/AddOrUpdateBooking.jsx
- src/pages/Store/Stock/index.jsx
- src/routes/private/Store.jsx
- src/state/QueryKeys.jsx
- src/state/Store.jsx
- src/util/Schema/index.jsx
Added store/stock booking and log
> Added store/stock booking and log

- src/pages/Commercial/LC/index.jsx
- src/pages/Common/MultiColor/Log/index.jsx
- src/pages/DyeingAndIron/DyeingDashboard/Content/Content.jsx
- src/pages/DyeingAndIron/DyeingDashboard/Content/divContent.jsx
- src/pages/DyeingAndIron/DyeingDashboard/Header.jsx
- src/pages/DyeingAndIron/DyeingDashboard/index.jsx
- src/pages/DyeingAndIron/FinishingBatch/Details/Information.jsx
- src/pages/DyeingAndIron/FinishingBatch/Entry/Header.jsx
- src/pages/DyeingAndIron/FinishingBatch/index.jsx
- src/pages/DyeingAndIron/ProductionCapacity/AddOrUpdate.jsx
- src/pages/DyeingAndIron/ProductionCapacity/index.jsx
- src/pages/DyeingAndIron/ThreadBatch/Details/Information.jsx
- src/pages/DyeingAndIron/ThreadBatch/Entry/Header.jsx
- src/pages/DyeingAndIron/ThreadBatch/Entry/index.jsx
- src/pages/DyeingAndIron/ZipperBatch/Details/Information.jsx
- src/pages/DyeingAndIron/ZipperBatch/Entry/Header.jsx
- src/pages/DyeingAndIron/ZipperBatch/Entry/index.jsx
- src/pages/Order/Details/Entry/Header.jsx
- src/routes/private/DyeingAndIron.jsx
- src/state/Dyeing.jsx
- src/state/QueryKeys.jsx
- src/ui/Others/DatePicker/index.jsx
- src/ui/Others/index.jsx
- src/ui/index.jsx
- src/util/Schema/index.jsx
Added new pages Dyeing Dashboard & Production Capacity 
- Add/update/delete
> ci: :sparkles: Added 2 new pages Production capacity & Dyeing Dashboard

- src/pages/DyeingAndIron/FinishingBatch/Entry/Header.jsx
- src/pages/DyeingAndIron/FinishingBatch/Entry/TableView.jsx
- src/pages/DyeingAndIron/FinishingBatch/index.jsx
- src/pages/DyeingAndIron/ThreadBatch/Entry/Header.jsx
- src/pages/DyeingAndIron/ThreadBatch/index.jsx
- src/pages/DyeingAndIron/ZipperBatch/Entry/Header.jsx
- src/pages/DyeingAndIron/ZipperBatch/Entry/index.jsx
- src/pages/DyeingAndIron/ZipperBatch/index.jsx
- src/state/Other.jsx
- src/state/QueryKeys.jsx
- src/util/Schema/index.jsx
some bug fixes, initial slot implementation, finishing batch view table on entry
> some bug fixes, initial slot implementation, finishing batch view table on entry

- src/pages/Common/Tape/Log/TransferLog/AddOrUpdate.jsx
- src/pages/Common/Tape/Log/TransferLog/index.jsx
- src/pages/Common/Tape/SFG/Transfer.jsx
- src/pages/Common/Transfer/EntryUpdate/Update.jsx
- src/pages/Common/Transfer/EntryUpdate/index.jsx
- src/pages/Common/Transfer/index.jsx
- src/pages/DyeingAndIron/FinishingBatch/Entry/Header.jsx
- src/pages/LabDip/ZipperSwatch/index.jsx
- src/pages/Metal/Finishing/Log/Production/index.jsx
- src/pages/Metal/Finishing/Production/index.jsx
- src/pages/Metal/TeethColoring/Log/Production/index.jsx
- src/pages/Metal/TeethColoring/Production/index.jsx
- src/pages/Metal/TeethMolding/Log/Production/index.jsx
- src/pages/Metal/TeethMolding/Log/Transfer/index.jsx
- src/pages/Metal/TeethMolding/Production/index.jsx
- src/pages/Nylon/MetallicFinishing/Production/index.jsx
- src/pages/Nylon/PlasticFinishing/Production/index.jsx
- src/pages/Slider/Coloring/Log/ProductionLog/index.jsx
- src/pages/Slider/Coloring/Log/TransactionLog/AddOrUpdate.jsx
- src/pages/Slider/Coloring/Production/index.jsx
- src/pages/Slider/SliderAssembly/Log/ProductionLog/AddOrUpdateProd.jsx
- src/pages/Slider/SliderAssembly/Log/ProductionLog/AddOrUpdateStockProd.jsx
- src/pages/Slider/SliderAssembly/Log/ProductionLog/index.jsx
- src/pages/Vislon/Finishing/Log/Production/index.jsx
- src/pages/Vislon/Finishing/Production/index.jsx
- src/pages/Vislon/TeethMolding/Log/Production/index.jsx
- src/pages/Vislon/TeethMolding/Log/Transfer/index.jsx
- src/pages/Vislon/TeethMolding/Production/index.jsx
- src/state/index.jsx
- src/util/Schema/index.jsx
Added new fields for Dyed Store & Tape sfg transfer for tape orders
> ci: :sparkles: Added new fields for Dyed Store & Tape sfg transfer for tape orders

- src/pages/DyeingAndIron/FinishingBatch/Entry/Header.jsx
- src/pages/Store/Section/AddOrUpdate.jsx
- src/pages/Store/Section/index.jsx
- src/pages/Store/Type/AddOrUpdate.jsx
- src/pages/Store/Type/index.jsx
- src/pages/Store/Vendor/AddOrUpdate.jsx
- src/pages/Store/Vendor/index.jsx
Store and Finishing Batch bug fixes
> Store and Finishing Batch bug fixes

- src/components/Pdf/BatchReportDateWise/index.jsx
- src/components/Pdf/BatchReportDateWise/utils.jsx
- src/pages/Planning/DateWiseBatchReport/index.jsx
- src/pages/Planning/FinishingDashboard/Content/Content.jsx
- src/pages/Report/DailyProduction/index.jsx
- src/routes/private/Planning.jsx
- src/state/Planning.jsx
- src/state/QueryKeys.jsx
Implement DateWise Batch Report feature with PDF generation capabilities. Clean up code by removing commented-out sections for better clarity.
> Add DateWise Batch Report functionality and PDF generation

- src/components/Pdf/DailyProduction/index.jsx
- src/components/Pdf/PackingListSticker/index.jsx
- src/components/Pdf/ProductionStatement/index.jsx
- src/components/Pdf/ProductionStatement/utils.jsx
- src/components/Pdf/ZipperChallan/index.jsx
- src/pages/Report/ProductionStatement/Header.jsx
- src/pages/Report/ProductionStatement/index.jsx
- src/routes/private/Report.jsx
- src/state/QueryKeys.jsx
- src/state/Report.jsx
Introduce functionality for generating a Production Statement report with date filters and PDF output. Align table columns and simplify bold logic in the PDF. Add grand total calculations to the Daily Production PDF and update quantity labels in related documents.
> Add Production Statement report with PDF generation and date filters

- src/components/Pdf/ProductionStatement/index.jsx
- src/pages/Delivery/WarehouseRecv/index.jsx
Simplify grand total calculations in the ProductionStatement component and enhance data handling in the WarehouseRecv component. Clean up unused code to improve maintainability.
> Refactor grand total calculations and data handling improvements

- src/util/Schema/index.jsx
Remove unnecessary fields from the challan entry schema and update default values accordingly.
> Fix challan entry schema and default values

- src/components/Pdf/ProformaInvoice/utils.jsx
Change the labels from "Party" to "Proforma For" and update the corresponding address fields to reflect factory information in PI PDF.
> Update labels for factory information in PI PDF header

- src/components/Pdf/ZipperTravelCard/index.jsx
Introduce a color column in the Zipper Travel Card and modify the table layout to accommodate the new column.
> Add color column to Zipper Travel Card and adjust table layout

- src/pages/Slider/Coloring/RMStock/index.jsx
Reorganize imports for clarity and simplify the instantiation of PageInfo in the RMStock component.
> Refactor RMStock component imports and PageInfo instantiation

- src/components/Pdf/ZipperTravelCard/index.jsx
- src/pages/Delivery/Challan/Entry/Header.jsx
- src/pages/DyeingAndIron/ZipperBatch/Details/Table.jsx
- src/pages/DyeingAndIron/ZipperBatch/Entry/index.jsx
- src/pages/DyeingAndIron/ZipperBatch/index.jsx
- src/pages/Report/DailyProduction/Excel/index.jsx
- src/pages/Report/DailyProduction/Header.jsx
- src/pages/Report/Order/Header.jsx
- src/pages/Report/Order/index.jsx
- src/pages/Report/ProductionStatement/Excel/index.jsx
- src/pages/Report/ProductionStatement/Header.jsx
- src/routes/private/Report.jsx
- src/state/QueryKeys.jsx
- src/state/Report.jsx
Introduce a new Orders report page and enhance accuracy in tape calculations by incorporating input quantity. Update related components to reflect these changes.
> Add Orders report page and improve tape calculations

- src/components/Pdf/ConeSticker/index.jsx
Improved the text formatting in the ConeSticker PDF by adjusting font sizes and adding line breaks for enhanced readability.
> Adjust text formatting in ConeSticker PDF for better readability

- src/components/Pdf/ProformaInvoice/index.jsx
- src/pages/LabDip/Info/ByUUID/Information.jsx
- src/pages/LabDip/Recipe/index.jsx
- src/util/Schema/index.jsx
Update the header label from 'Sub Streat' to 'Substrate', enhance the order number check for better reliability, and adjust the layout for the PI PDF thread.
> fIx: PI thread table layout improved and Lab Dip issue fixed

- src/components/Pdf/CashInvoice/index.jsx
- src/components/Pdf/ProformaInvoice/index.jsx
- src/lib/NumToWord.jsx
Enhance the Cash and Proforma Invoice PDFs by updating style formatting, implementing a function to convert total values to words, and improving the formatting of unit prices and values.
> Update PDF formatting and add currency conversion to words

- src/pages/Delivery/Challan/index.jsx
- src/pages/Delivery/PackingList/index.jsx
- src/pages/Order/Details/index.jsx
- src/state/Delivery.jsx
- src/state/QueryKeys.jsx
added Taple extra status select in Packing-list, Challan and order details index api fix
> added Taple extra status select in Packing-list, Challan and order details index api fix

- src/pages/DyeingAndIron/ZipperBatch/Entry/index.jsx
Extract the tape weight calculation into a utility function for improved readability and maintainability of the code.
> Refactor tape weight calculation logic into utility function

- src/pages/Order/columns.jsx
- src/pages/Report/Bulk/index.jsx
- src/pages/Report/DailyChallan/index.jsx
- src/pages/Report/DailyProduction/Excel/index.jsx
- src/pages/Report/DeliveryStatement/index.jsx
- src/pages/Report/LC/index.jsx
- src/pages/Report/Order/index.jsx
- src/pages/Report/PIRegister/index.jsx
- src/pages/Report/PIToBeSubmit/index.jsx
- src/pages/Report/ProductionReportDirector/thread.jsx
- src/pages/Report/ProductionReportDirector/zipper.jsx
- src/pages/Report/ProductionReportS&M/thread.jsx
- src/pages/Report/ProductionReportS&M/zipper.jsx
- src/pages/Report/ProductionStatement/Excel/index.jsx
- src/pages/Report/Sample/index.jsx
- src/pages/Report/ThreadProductionStatus/index.jsx
- src/pages/Report/ZipperProductionStatus/index.jsx
- src/pages/Thread/Conneing/index.jsx
- src/pages/Thread/Log/Production/index.jsx
- src/pages/Thread/Order/index.jsx
Replace instances of LinkWithCopy and LinkOnly with CustomLink for improved navigation and consistency across various report components. Simplify row span logic in Excel report components for better readability.
> Refactor navigation links in report components to CustomLink

- src/components/Pdf/ProductionStatement/index.jsx
- src/pages/Commercial/Dashboard/index.jsx
- src/pages/Commercial/LC/Details/Information.jsx
- src/pages/Commercial/LC/index.jsx
- src/pages/Commercial/PI/index.jsx
- src/pages/Report/DailyProduction/Excel/index.jsx
- src/pages/Report/ProductionStatement/Excel/index.jsx
Replace `LinkWithCopy` with `CustomLink` for better navigation and include packing numbers in item descriptions.
> Refactor navigation links and enhance item descriptions

- src/components/Pdf/DailyProduction/index.jsx
- src/components/Pdf/ProductionStatement/index.jsx
- src/pages/Report/DailyProduction/Excel/index.jsx
- src/pages/Report/ProductionStatement/Excel/index.jsx
Enhance the ProductionStatement PDF by adding packing numbers and improving item display logic. Optimize item summary logic in the Excel report for better clarity and structure. Simplify the logic for adding 'Order Wise Total' in Daily Production reports.
> Refactor production reports for clarity and additional data

- src/components/Pdf/DailyProduction/index.jsx
- src/components/Pdf/ProductionStatement/index.jsx
- src/pages/Report/Bulk/index.jsx
- src/pages/Report/DailyProduction/Excel/index.jsx
- src/pages/Report/DailyProduction/index.jsx
- src/pages/Report/Order/index.jsx
- src/pages/Report/ProductionStatement/Excel/index.jsx
- src/pages/Report/ProductionStatement/Header.jsx
- src/pages/Report/ProductionStatement/index.jsx
- src/pages/Report/Sample/index.jsx
- src/state/QueryKeys.jsx
- src/state/Report.jsx
Introduce additional filters and detailed calculations for order totals in production statement and daily production reports. Update order link logic to handle different order types and improve PDF generation functionality.
> Enhance production statement and daily reports with new filters and calculations

- src/components/Pdf/ThreadOrderSheet/index.jsx
- src/components/Pdf/ThreadOrderSheet/utils.jsx
- src/components/Pdf/ZipperChallan/index.jsx
Enhance clarity in the Thread Order PDF by updating header and field labels. Include carton weight in the packing list numbers for better information.
> Update PDF headers Thread order sheet and include carton weight in packing list In challan PDF

- src/pages/Report/ProductionStatement/Header.jsx
- src/pages/Report/ProductionStatement/index.jsx
- src/state/Other.jsx
- src/state/QueryKeys.jsx
- src/state/Report.jsx
added order selection field in report/production-satement
> added order selection field in report/production-satement

- src/components/Pdf/ProductionStatement/index.jsx
- src/components/Pdf/ThreadOrderSheet/index.jsx
- src/components/Pdf/ThreadPackeListSticker/index.jsx
- src/components/Pdf/ThreadTravelCard/index.jsx
- src/pages/DyeingAndIron/ThreadBatch/Details/index.jsx
- src/pages/Report/ProductionStatement/Excel/index.jsx
Introduce expected yarn requirement calculations and improve precision in Thread Order and Travel Card PDFs. Update the Thread Packing List PDF and production statement accordingly.
> Enhance Thread Order and Packing List PDFs with Yarn Calculations

- src/components/Pdf/BatchReportDateWise/index.jsx
Adjust the column widths in the BatchReportDateWise PDF component for improved layout and readability.
> Update column widths in BatchReportDateWise PDF component

- src/pages/Store/Stock/index.jsx
Introduce a new 'Priority' column in the Stock table that utilizes a StatusButton for better visual representation of priority status.
> Add 'Priority' column with StatusButton in Stock table

- src/components/Pdf/BatchReportDateWise/index.jsx
- src/components/Pdf/ThreadBulkRecipe/index.jsx
- src/components/Pdf/ThreadBulkRecipe/utils.jsx
- src/components/Pdf/ThreadTravelCard/utils.jsx
- src/pages/DyeingAndIron/ThreadBatch/Details/index.jsx
- src/pages/Planning/DateWiseBatchReport/index.jsx
Adjust bulk and total yarn quantities to three decimal places in PDF components and reorder columns in the Batch Report for improved consistency across views.
> fix: Three digit format  and reorder Datewise Batch Report columns for consistency

- src/components/Pdf/ThreadTravelCard/utils.jsx
Enhance the display of yarn quantity by including the total expected weight in the ThreadTravelCard component.
> Update yarn quantity display to include total expected weight in ThreadTravelCard

- src/pages/Nylon/PlasticFinishing/Log/index.jsx
- src/util/Schema/index.jsx
Update the `merchandiser_uuid` field to be nullable and improve code formatting in the Log component.
> Make merchandiser_uuid nullable and clean up Log component formatting

- src/pages/LabDip/Info/index.jsx
- src/pages/Store/Stock/AgainstOrderTransfer.jsx
Add a new column for recipes with links and approval statuses in the LabDip Info table. Update the label for the tape option in the AgainstOrderTransfer component for clarity.
> Add recipe column and update tape option label

- src/components/Pdf/ThreadBulkRecipe/index.jsx
- src/pages/DyeingAndIron/ThreadBatch/Details/index.jsx
Enhance the precision of bulk and quantity calculations from three to five decimal places for improved accuracy in the application. Update the document title to reflect the correct context.
> Increase precision for bulk and quantity calculations in ThreadBulkRecipe and ThreadBatch details

- src/components/Pdf/ThreadBulkRecipe/index.jsx
- src/components/Pdf/ThreadBulkRecipe/utils.jsx
- src/components/Pdf/ZipperBulkRecipe/index.jsx
- src/components/Pdf/ZipperBulkRecipe/utils.jsx
- src/pages/DyeingAndIron/ZipperBatch/Details/Table.jsx
- src/pages/DyeingAndIron/ZipperBatch/Details/index.jsx
- src/pages/DyeingAndIron/ZipperBatch/Entry/columns.jsx
- src/pages/Report/DailyProduction/index.jsx
Improve PDF generation logic in ZipperBulkRecipe by implementing new batch entry calculations and refining data handling. Simplify the layout of ThreadBulkRecipe and DailyProduction reports for clarity and cleaner presentation.
> Enhance ZipperBulkRecipe and DailyProduction PDF generation

- src/components/Pdf/ThreadOrderSheet/index.jsx
Enhance consistency and clarity in the ThreadOrderSheet PDF by updating labels and adjusting layout elements.
> Style: Update labels and layout in ThreadOrderSheet PDF for clarity

- src/pages/Common/Transfer/index.jsx
Import the CustomLink component in the Transfer page for enhanced functionality.
> Add CustomLink component to Transfer page

- src/components/Pdf/ZipperChallan/index.jsx
- src/pages/Report/PIToBeSubmit/index.jsx
Correct the uuid assignment to use the appropriate value from the orderNumber object.
> Fix uuid assignment in PIToBeSubmit component

- src/pages/Report/ProductionStatement/Header.jsx
Enhance the API call in the ProductionStatement header to support pagination, improving data retrieval efficiency.
> Update API call in ProductionStatement header for pagination

- src/components/Pdf/ProformaInvoice/utils.jsx
Enhance the layout structure of the ProformaInvoice header for improved readability and organization.
> Refactor ProformaInvoice header layout structure

- src/pages/Report/ThreadProductionStatus/thread-production.jsx
The DateTime component now displays time for various date fields instead of just the date.
> Update DateTime component to display time for date fields

- src/pages/Report/ThreadProductionStatusOrderWise/index.jsx
Introduce a new column for 'Warehouse' in the production status report to enhance data visibility.
> Add warehouse column to production status report

- src/pages/Order/columns.jsx
Reorder the definition of the 'order_number_wise_rank' column to improve code clarity.
> Refactor order_number_wise_rank column for clarity

- package-lock.json
- package.json
Downgraded the versions of @handsontable/react and handsontable to 14.6.1 to fix the inability to copy and paste values.
> Downgraded the versions of @handsontable/react and handsontable to 14.6.1 to fix the inability to copy and paste values.

- src/components/Pdf/ProformaInvoice/index.jsx
- src/pages/Common/Dashboard/index.jsx
- src/pages/Common/TapeAssign/index.jsx
- src/pages/DyeingAndIron/ZipperBatch/index.jsx
- src/routes/private/Common.jsx
- src/state/Common.jsx
- src/state/QueryKeys.jsx
Correct the logic for selecting tape assignments to include support for Metal versions 3 and 4.5.
> Fix tape assignment selection for Metal 3 and 4.5

- src/pages/Delivery/PackingList/index.jsx
Improve button click handling and define the URL for the packing list in the Packing List component.
> Refactor Packing List component for button handling and URL definition

- src/pages/Report/OrderSummary/index.jsx
Streamline data transformation and improve URL construction in the Order Summary component. Remove unused console logs to enhance code cleanliness.
> Refactor Order Summary component for clarity and performance

- src/pages/Report/ZipperProductionStatus/index.jsx
Improve readability and performance by updating the JSX structure in production status components.
> Refactor JSX structure for production status components

- src/pages/Delivery/Challan/Entry/index.jsx
Format the delivery_date to 'yyyy-MM-dd HH:mm:ss' prior to submission to ensure consistency in date handling.
> Format delivery_date before submission

- src/components/Pdf/CashInvoice/utils.jsx
- src/pages/Delivery/PackingList/Entry/DyanamicDeliveryFIeld.jsx
- src/pages/Report/DeliveryReport/Thread.jsx
- src/pages/Report/DeliveryReport/Zipper.jsx
- src/pages/Report/DeliveryReport/index.jsx
- src/routes/private/Report.jsx
- src/state/QueryKeys.jsx
- src/state/Report.jsx
Update the invoice header to display 'Invoice For' along with the factory name. Introduce new delivery report components and query keys for zipper and thread functionalities.
> Update invoice header and add delivery report components

- src/components/Pdf/DailyProduction/index.jsx
- src/pages/Report/DailyProduction/Excel/index.jsx
Enhance the robustness of API requests by implementing better error handling mechanisms, ensuring clearer feedback for users in case of failures.
> Improve error handling in API requests

- src/components/Pdf/DailyProduction/index.jsx
- src/pages/Report/ProductionStatement/production/Excel/index.jsx
Introduce calculations for grand totals specific to Zipper and Thread types in the daily production reports, enhancing data visibility and reporting accuracy.
> Add grand totals for Zipper and Thread types in daily production reports

- src/components/Pdf/ProformaInvoiceOnlyDzn/index.jsx
- src/components/Pdf/ProformaInvoiceOnlyDzn/utils.jsx
- src/components/Pdf/ProformaInvoiceOnlyPCS/index.jsx
- src/components/Pdf/ProformaInvoiceOnlyPCS/utils.jsx
- src/components/Pdf/ThreadBulkRecipe/index.jsx
- src/pages/Commercial/PI/Details/index.jsx
- src/pages/Delivery/Challan/index.jsx
- src/pages/Delivery/PackingList/index.jsx
- src/pages/DyeingAndIron/ThreadBatch/Details/index.jsx
- src/pages/LabDip/Recipe/Entry/index.jsx
Introduce an index to recipe entries for better tracking and add a color column to the delivery tables for improved data representation.
> Enhance recipe entry with index and add color column in delivery tables

- src/components/Pdf/ManualProformaInvoice/index.jsx
- src/components/Pdf/ManualProformaInvoice/utils.jsx
- src/components/Pdf/ProformaInvoice/index.jsx
- src/components/Pdf/ProformaInvoiceOnlyDzn/index.jsx
- src/components/Pdf/ProformaInvoiceOnlyPCS/index.jsx
- src/pages/Commercial/ManualPI/Details/Table/index.jsx
- src/pages/Commercial/ManualPI/Details/index.jsx
- src/pages/Commercial/ManualPI/Entry/Header.jsx
- src/pages/Commercial/ManualPI/Entry/index.jsx
- src/pages/Commercial/ManualPI/Entry/spreadsheets/thread-manual-pi-spreadsheet.jsx
- src/pages/Commercial/ManualPI/index.jsx
- src/ui/Dynamic/HandsonSpreadSheet/test/index.jsx
- src/util/Schema/index.jsx
Enhance the Manual Proforma Invoice components by separating zipper and thread entries, updating value formatting, and conditionally hiding columns in the table based on the entry type.
> Refactor Manual PI components for improved handling and display

- src/pages/Order/Details/_components/Table/Column.jsx
- src/pages/Order/Details/_components/Table/index.jsx
- src/pages/Order/Details/_components/ViewByStyle/Column.jsx
- src/pages/Order/Details/_components/ViewByStyle/Table.jsx
- src/pages/Report/Bulk/index.jsx
- src/routes/private/Report.jsx
- src/state/QueryKeys.jsx
- src/state/Report.jsx
Remove the from/to date filters and introduce a new access control for showing zero balance. Add a new column for delivered balance and enable filtering for the party column. Update the data fetching logic to utilize the new bulk report functionality.
> Report/Bulk: Enhance filtering and access controls

- src/pages/Planning/FinishingBatch/Entry/Header.jsx
- src/pages/Planning/FinishingBatch/Entry/TableView.jsx
- src/pages/Planning/FinishingBatch/Entry/quantity-card.jsx
- src/pages/Report/PackingList/index.jsx
- src/pages/Store/Stock/index.jsx
- src/routes/private/Report.jsx
- src/state/QueryKeys.jsx
- src/state/Report.jsx
Introduce a new Packing List Report and improve the production capacity tracking in the planning entry. Additionally, add new columns to the stock and planning entry tables for better data representation.
> Add Packing List Report and enhance production capacity tracking

- src/pages/Report/PackingList/index.jsx
Comment out the 'CTN. Qty.' column in the table to resolve a minor issue.
> Fix minor bug in table column configuration

- src/pages/Commercial/LC/Details/Information.jsx
- src/pages/Commercial/LC/Details/Table/index.jsx
- src/pages/Commercial/LC/Entry/DynamicProgression.jsx
- src/pages/Commercial/LC/Entry/Header.jsx
- src/pages/Order/Details/_components/Information/Item.jsx
- src/util/Schema/index.jsx
Introduce functionality to retrieve and display special requirements associated with orders in the Order/details page. This enhancement improves the user experience by providing relevant information directly in the item description.
> Add special requirement handling in Order/details page

- src/pages/Commercial/LC/Details/Information.jsx
- src/pages/Commercial/LC/Details/Table/index.jsx
- src/pages/Commercial/LC/Details/utils.js
Update the date time format for various LC details to a new standardized format, improving consistency across the application.
> Change date time format for LC details

- src/pages/Delivery/GatePass/index.jsx
- src/pages/Delivery/PackingList/index.jsx
- src/pages/Delivery/WarehouseRecv/index.jsx
Implement functionality to manage gate pass and warehouse received dates within the Delivery pages. This includes updates to the data structure and UI components to reflect these new fields.
> Add gate pass and warehouse received date functionality in Delivery pages

- src/components/Modal/Update/index.jsx
- src/pages/Commercial/LC/Entry/Header.jsx
- src/pages/Commercial/LC/Entry/index.jsx
Update the modal's appearance and improve the logic within the Header component for better performance and readability.
> Refactor modal styling and optimize Header component logic

- package.json
Introduce a deploy script in package.json to streamline the deployment process by pulling the latest changes and building the project.
> Add deploy script for automated deployment

- src/pages/Delivery/Log/WarehouseOut/index.jsx
- src/pages/Delivery/Log/WarehouseRCV/index.jsx
- src/pages/Delivery/Log/index.jsx
- src/state/Delivery.jsx
- src/state/QueryKeys.jsx
Introduce components and hooks for managing Warehouse Received and Warehouse Out logs, enhancing the delivery logging functionality.
> Add Warehouse Received and Warehouse Out logs with hooks and components

- src/pages/Report/Bulk/index.jsx
- src/pages/Store/Log/AgainstOrder/index.jsx
- src/pages/Store/Log/PurchaseLog/index.jsx
- src/pages/Store/LogAccessories/AgainstOrder/AddOrUpdate.jsx
- src/pages/Store/LogAccessories/AgainstOrder/index.jsx
- src/pages/Store/LogAccessories/Booking/AddOrUpdate.jsx
- src/pages/Store/LogAccessories/Booking/AgainstOrderTransfer.jsx
- src/pages/Store/LogAccessories/Booking/MaterialTrx.jsx
- src/pages/Store/LogAccessories/Booking/index.jsx
- src/pages/Store/LogAccessories/PurchaseLog/AddOrUpdate.jsx
- src/pages/Store/LogAccessories/PurchaseLog/index.jsx
- src/pages/Store/LogAccessories/Trx/AddOrUpdate.jsx
- src/pages/Store/LogAccessories/Trx/index.jsx
- src/pages/Store/LogAccessories/index.jsx
- src/routes/private/Report.jsx
- src/routes/private/Store.jsx
- src/state/QueryKeys.jsx
- src/state/Report.jsx
- src/state/Store.jsx
Refactor the side navigation bar to distinguish between Store RM and Store Accessories, enhancing organization and clarity for users.
> Separate Store RM and Accessories in Side Navigation Bar

- src/pages/Delivery/Log/WarehouseOut/index.jsx
- src/pages/Delivery/Log/WarehouseRCV/index.jsx
- src/pages/Report/ProductionSummary/ItemWise.jsx
- src/pages/Report/ProductionSummary/ItemZipperEndWise.jsx
- src/pages/Report/ProductionSummary/index.jsx
- src/routes/private/Report.jsx
- src/state/QueryKeys.jsx
- src/state/Report.jsx
Introduce an item description column in the delivery log and implement a new report for production summary, enhancing data visibility and reporting capabilities.
> Add item description to delivery log and new production summary report

- src/components/Pdf/OrderSheetByStyle/index.jsx
- src/pages/Common/Transfer/index.jsx
- src/pages/Store/Log/AgainstOrder/index.jsx
- src/pages/Store/Log/Booking/index.jsx
- src/pages/Store/Log/PurchaseLog/index.jsx
- src/pages/Store/Log/Trx/index.jsx
- src/pages/Store/LogAccessories/AgainstOrder/index.jsx
- src/pages/Store/LogAccessories/Booking/index.jsx
- src/pages/Store/LogAccessories/PurchaseLog/index.jsx
- src/pages/Store/LogAccessories/Trx/index.jsx
- src/state/Dyeing.jsx
- src/state/QueryKeys.jsx
- src/state/Store.jsx
Enhance order PDF generation by including a total quantity for each description. Implement date filtering for dyeing store and store log views to improve data retrieval and user experience.
> Add total description in order PDF and date filtering in dyeing store

- src/pages/Profile/AddOrUpdate.jsx
- src/pages/Profile/Information.jsx
- src/pages/Profile/index.jsx
- src/routes/private/Profile.jsx
- src/routes/private/index.jsx
- src/state/Admin.jsx
- src/state/QueryKeys.jsx
Introduce a new profile management system that allows users to update their information and reset their passwords. This includes the addition of necessary hooks, components, and routes to support these features.
> Add Profile management functionality with user update and reset password features

- src/pages/LabDip/ThreadSwatch/index.jsx
- src/pages/LabDip/ZipperSwatch/index.jsx
- src/pages/Order/Details/ByOrderDescriptionUUID/index.jsx
- src/pages/Order/Details/Entry/spread-sheets/full-order.jsx
- src/pages/Order/Details/Entry/spread-sheets/slider.jsx
- src/pages/Order/Details/Entry/spread-sheets/tape.jsx
- src/pages/Order/Details/Entry/useGenerateFieldDefs.jsx
- src/pages/Order/Details/_components/Table/Column.jsx
- src/pages/Order/Details/_components/Table/index.jsx
- src/pages/Thread/Order/Details/Table/index.jsx
- src/pages/Thread/Order/Entry/spreadsheets/order-entry-spreadsheet.jsx
- src/ui/Dynamic/HandsonSpreadSheet/test/index.jsx
Introduce a new column in the LabDip tables to indicate whether a dyeing batch has been created, featuring a status button for better visual representation.
> Add Dyeing Batch Created column with status button to LabDip tables

- src/pages/Commercial/Cash/Entry/Header.jsx
- src/pages/Commercial/LC/Entry/Header.jsx
- src/pages/Commercial/PI/Entry/Header.jsx
- src/pages/Thread/Conneing/Production.jsx
- src/state/Other.jsx
Refactor API call parameters for consistency and improve form validation in the Conning Production form. This update enhances readability and ensures better handling of form inputs.
> Update API parameters and enhance form validation logic

- src/pages/Report/Bulk/index.jsx
- src/pages/Report/DailyChallan/index.jsx
- src/pages/Report/DeliveryReport/Thread.jsx
- src/pages/Report/DeliveryReport/Zipper.jsx
- src/pages/Report/OrderStatus/Thread.jsx
- src/pages/Report/OrderStatus/Zipper.jsx
- src/pages/Report/OrderTracking/index.jsx
- src/pages/Report/PackingList/index.jsx
- src/pages/Report/ProductionStatement/order/index.jsx
- src/pages/Report/ProductionStatement/production/index.jsx
- src/pages/Report/Sample/index.jsx
- src/pages/Report/ThreadProductionStatusOrderWise/index.jsx
- src/pages/Report/ZipperProductionStatus/index.jsx
Corrected the handling of Excel values in reports, added a received status column in the delivery report, and improved data fetching on click for the production statement report.
> Fix report Excel values and enhance data fetching in reports

- src/pages/Store/Log/AgainstOrder/index.jsx
- src/pages/Store/Log/Booking/index.jsx
- src/pages/Store/Log/Trx/index.jsx
- src/pages/Store/LogAccessories/AgainstOrder/index.jsx
- src/pages/Store/LogAccessories/Booking/index.jsx
- src/pages/Store/LogAccessories/Trx/index.jsx
Change the URL for material transaction against order to ensure correct routing.
> Update URL for material transaction against order

- src/components/Pdf/OrderStatement/index.jsx
- src/components/Pdf/OrderStatement/thread/index.jsx
- src/components/Pdf/OrderStatement/utils.jsx
Improve the accuracy of total order calculations in the order summary and enhance null safety for order entries throughout the codebase.
> Enhance order summary total calculations and improve null safety

- src/pages/Report/Consumption/index.jsx
- src/pages/Report/DailyProduction/Excel/index.jsx
- src/pages/Report/PackingList/index.jsx
- src/pages/Report/ProductionStatement/ProductionV2/Excel/index.jsx
- src/pages/Report/ProductionStatement/ProductionV2/Header.jsx
- src/pages/Report/ProductionStatement/ProductionV2/index.jsx
- src/pages/Report/ProductionStatement/index.jsx
- src/pages/Report/ProductionStatement/orderV2/Excel/index.jsx
- src/pages/Report/ProductionStatement/orderV2/Header.jsx
- src/pages/Report/ProductionStatement/orderV2/index.jsx
- src/pages/Report/utils.jsx
- src/routes/private/Report.jsx
- src/state/QueryKeys.jsx
- src/state/Report.jsx
Introduce a new report page for consumption, enabling users to download reports in PDF and Excel formats. This update enhances reporting capabilities and user experience.
> Add PDF and Excel download functionality for consumption report

- src/pages/Report/ProductionStatement/order-v2/index.jsx
- src/pages/Report/ProductionStatement/production-v2/index.jsx
Update the parameter name in the PDF handling function to improve clarity and ensure correct functionality in production.
> Fix production statement bug in PDF handling

- src/pages/Report/OrderSummary/TransposedTable.jsx
- src/pages/Report/OrderSummary/index.jsx
Introduce a new table to display a transposed order summary, enhancing data presentation and usability.
> Add report/order-summary table functionality

- src/pages/Report/Bulk/index.jsx
- src/pages/Report/DailyChallan/index.jsx
- src/pages/Report/DeliveryReport/Thread.jsx
- src/pages/Report/DeliveryReport/Zipper.jsx
- src/pages/Report/Order/index.jsx
- src/pages/Report/OrderStatus/Thread.jsx
- src/pages/Report/OrderStatus/Zipper.jsx
- src/pages/Report/OrderTracking/index.jsx
- src/pages/Report/PIRegister/index.jsx
- src/pages/Report/PackingList/index.jsx
- src/pages/Report/Sample/index.jsx
- src/pages/Report/ThreadProductionStatusOrderWise/index.jsx
- src/pages/Report/ZipperProductionStatus/index.jsx
Update date formatting in various report fields to ensure consistency and correct display of dates. Adjustments include changing formats from 'dd MMM, yy' to 'dd/MM/yy' across multiple date fields.
> Fix date formatting issues in reports

- src/pages/Delivery/Log/WarehouseNotOut/index.jsx
- src/pages/Delivery/Log/index.jsx
- src/pages/Order/Details/_components/Information/index.jsx
- src/pages/Order/Details/index.jsx
- src/pages/Order/columns.jsx
- src/state/Delivery.jsx
- src/state/QueryKeys.jsx
- src/ui/Others/Button/index.jsx
Introduce a new delivery report log and an initial WhatsApp feature for sending order messages. This update enhances the user interface by integrating the WhatsApp button and improves data handling for warehouse logs.
> Add Delivery Report Log and WhatsApp Feature

- src/pages/Delivery/Log/WarehouseNotOut/index.jsx
- src/pages/Delivery/Log/WarehouseOut/index.jsx
- src/pages/Delivery/Log/WarehouseRCV/index.jsx
Enhance the item description display in delivery logs to accommodate multiple links, improving user navigation and information accessibility.
> Update item description handling in delivery logs to support multiple links

- src/pages/Order/Details/_components/Information/index.jsx
- src/pages/Order/Details/index.jsx
- src/pages/Order/columns.jsx
Refactor the marketing checked functionality to include a timestamp for when the marketing status is updated. Adjust the state management for better clarity and add a new column to display the marketing checked timestamp in the order details.
> Update marketing checked functionality and add timestamp to order details

- package-lock.json
- package.json
- src/components/Pdf/ThreadPackeListStickerV2/Barcode.jsx
- src/components/Pdf/ThreadPackeListStickerV2/index.jsx
- src/components/Pdf/ThreadPackeListStickerV2/utils.jsx
- src/pages/Delivery/PackingList/Details/index.jsx
- src/pages/Delivery/PackingList/index.jsx
Introduce a new feature for generating packing list PDFs, including barcode support. Update dependencies and modify existing components to accommodate the new PDF generation logic.
> Add PDF generation functionality with barcode support for packing lists

- src/components/Pdf/ThreadPackeListStickerV2/index.jsx
Modify column widths and colspan attributes to improve the layout of the packing list PDF.
> Adjust table layout for packing list PDF generation

- src/components/Pdf/ZipperChallan/index.jsx
Adjust the header height in the ZipperChallan component to improve layout consistency.
> Update header height in ZipperChallan component

- src/pages/Order/Details/_components/Table/index.jsx
- src/pages/Thread/Order/Details/Table/index.jsx
Ensure that price information is only displayed to users with the appropriate permissions.
> Fix price visibility based on permissions

- src/pages/Metal/Finishing/Production/Production.jsx
- src/pages/Report/Sample/index.jsx
Address a bug related to the maximum quantity transfer for floor operations, ensuring correct calculations based on order types and additional conditions.
> Fix floor max quantity transfer bug in CI

- src/pages/Delivery/Challan/Details/Information.jsx
- src/pages/Report/Sample/index.jsx
Correct the implementation of the challan info column to properly display the challan numbers from the data.
> Fix challan info column display issue

- src/components/Pdf/OrderSheetByStyle/utils.jsx
- src/pages/Delivery/Challan/Details/Information.jsx
- src/pages/Order/Details/ByOrderNumber/index.jsx
- src/pages/Report/Sample/index.jsx
Introduce a new column for challan quantity in the sample report and update relevant components to display delivery status and total challan calculations.
> Add challan quantity column to sample report

- src/pages/Commercial/PI/index.jsx
- src/pages/Nylon/PlasticFinishing/Production/Production.jsx
- src/pages/Nylon/PlasticFinishing/Production/index.jsx
Introduce a delete button for PI entries and a production modal that activates when a slider is provided for nylon plastic. These enhancements improve user interaction and functionality.
> Add delete button for PI and production modal for nylon plastic

- src/pages/Metal/Finishing/Production/index.jsx
- src/pages/Nylon/MetallicFinishing/Production/Production.jsx
- src/pages/Nylon/MetallicFinishing/Production/index.jsx
- src/pages/Vislon/Finishing/Production/Production.jsx
- src/pages/Vislon/Finishing/Production/index.jsx
Introduce a production modal that activates for all floor finishing options when a slider is provided, enhancing user interaction and functionality.
> Add production modal for floor finishing with slider provided

- src/pages/Common/Coil/SFG/TrxToDying.jsx
- src/pages/Common/Coil/SFG/index.jsx
- src/pages/Common/Tape/SFG/index.jsx
Introduce a modal for managing tape transfers to dyeing and store, enhancing user interaction and data handling for these operations.
> Add modal for tape transfer to dyeing and store

- src/pages/Common/Coil/Log/Tape-Dyeing-store/AddOrUpdate.jsx
- src/pages/Common/Coil/Log/Tape-Dyeing-store/index.jsx
- src/pages/Common/Coil/Log/index.jsx
- src/pages/Common/Tape/Log/Tape-Dyeing-store/AddOrUpdate.jsx
- src/pages/Common/Tape/Log/Tape-Dyeing-store/index.jsx
- src/pages/Common/Tape/Log/index.jsx
- src/pages/Delivery/PackingList-Bulk/Entry/index.jsx
- src/pages/Report/Sample/index.jsx
- src/routes/private/Report.jsx
- src/state/Common.jsx
- src/state/QueryKeys.jsx
Introduce new routes and components for managing tape dyeing and storage, enhancing the application's ability to handle related operations and improve user access controls.
> Add Tape preparation to dyeing and store logging functionality

- src/components/Pdf/CashInvoice/index.jsx
Correct the unit price calculation to ensure accurate formatting and adjust table widths for better layout consistency.
> Fix unit price calculation and adjust table widths

- src/pages/Report/OrderStatus/Thread.jsx
- src/pages/Report/OrderStatus/Zipper.jsx
Introduce new data fields for PI numbers, LC numbers, and batches in the OrderStatus and Zipper components. Improve rendering of these fields for better user experience.
> Enhance OrderStatus and Zipper components with additional data fields and improved rendering

- src/pages/Commercial/PI/Entry/index.jsx
- src/pages/Delivery/Quantity-Return/Entry/Header.jsx
- src/pages/Delivery/Quantity-Return/Entry/columns.jsx
- src/pages/Delivery/Quantity-Return/Entry/index.jsx
- src/pages/Delivery/Quantity-Return/index.jsx
- src/pages/Order/Details/Entry/index.jsx
- src/pages/Planning/FinishingBatch/Entry/Header.jsx
- src/pages/Planning/FinishingBatch/Entry/index.jsx
- src/pages/Planning/Overview/index.jsx
- src/pages/Thread/Order/Entry/index.jsx
- src/routes/private/Planning.jsx
- src/state/Dyeing.jsx
- src/state/Other.jsx
- src/state/QueryKeys.jsx
- src/ui/Others/DatePicker/index.jsx
- src/util/Schema/index.jsx
Refactor the Order Overview page for better organization and introduce bulk entry functionality in the planning section. This enhances user experience and streamlines operations.
> Separate Order Overview page and add bulk entry in planning

- src/pages/Planning/FinishingBatch/Entry/index.jsx
- src/pages/Report/OrderStatus/Zipper.jsx
Introduce new columns in the planning batch report and address a bug related to batch navigation.
> Report new columns and fix planning batch bug

- src/pages/Delivery/Challan/Entry/index.jsx
- src/pages/Report/OrderStatus/Thread.jsx
- src/pages/Report/OrderStatus/Zipper.jsx
- src/pages/Store/Receive/Entry/index.jsx
- src/pages/Store/ReceiveAccessories/Entry/index.jsx
Introduce bulk entry for store/receive operations and ensure required challan remarks are enforced during updates. Additionally, fix report column headers for better clarity.
> Add bulk entry functionality and fix report columns

- src/pages/Delivery/PackingList-Bulk/Entry/index.jsx
- src/pages/Delivery/PackingList/Entry/index.jsx
- src/pages/LabDip/Info/Entry/index.jsx
- src/pages/LabDip/Recipe/Entry/index.jsx
- src/pages/Report/OrderStatus/Thread.jsx
- src/pages/Report/OrderStatus/Zipper.jsx
Introduce bulk order processing for Labdip, including updates to recipe and packing list entries. This enhancement streamlines the creation and updating of multiple entries in a single request.
> Add bulk order functionality for Labdip

- src/pages/DyeingAndIron/ZipperBatch/Entry/index.jsx
Restore navigation functionality to the dyeing zipper batch component by uncommenting the relevant code.
> Fix navigation bug in dyeing zipper batch component

- src/pages/Admin/User/index.jsx
- src/pages/Commercial/LC/index.jsx
- src/pages/Delivery/PackingList/index.jsx
- src/pages/Planning/Overview/index.jsx
- src/pages/Report/ThreadBatch/index.jsx
- src/pages/Slider/Coloring/Production/index.jsx
Activate column filters for tables across user, commercial, delivery, planning, report, and slider pages to enhance data manipulation and user experience.
> Enable column filters for various tables

- src/pages/Report/OrderSummaryPL/Header.jsx
- src/pages/Report/OrderSummaryPL/Information.jsx
- src/pages/Report/OrderSummaryPL/TransposedTable.jsx
- src/pages/Report/OrderSummaryPL/index.jsx
- src/routes/private/Report.jsx
- src/state/QueryKeys.jsx
- src/state/Report.jsx
Introduce a new report for the packing list order summary, including necessary state management, routing, and UI components. This report allows users to view and interact with order details specific to packing lists.
> Add Packing List Order Summary Report

- src/pages/Order/columns.jsx
Introduce additional columns for actions, sample/bill/cash status, order number, buyer, party, marketing, merchandiser, factory, priority, created by, created date, and updated date to enhance data representation in the InfoColumns component.
> Add new columns to InfoColumns component

- src/components/Pdf/ChallanByDate/index.jsx
- src/pages/Delivery/Challan/ByDate/index.jsx
- src/pages/Delivery/PackingList-Bulk/index.jsx
- src/pages/Delivery/PackingList/index.jsx
- src/pages/Report/DeliveryReport/Thread.jsx
- src/pages/Report/DeliveryReport/Zipper.jsx
- src/pages/Report/DeliveryReport/utils.js
- src/pages/Report/LC/index.jsx
- src/pages/Report/OrderSheetSR/Thread.jsx
- src/pages/Report/OrderSheetSR/Zipper.jsx
- src/pages/Report/OrderSheetSR/index.jsx
- src/pages/Report/OrderSheetSR/utils.js
- src/pages/Report/Store/Store.jsx
- src/pages/Report/utils.jsx
- src/routes/private/Delivery.jsx
- src/routes/private/Report.jsx
- src/state/QueryKeys.jsx
- src/state/Report.jsx
Addressed multiple bugs including date/time errors and null join issues. Enhanced the packing list functionality to allow edit/delete access based on date ranges. Introduced new filters and reports for improved data handling.
> Fix various bugs and enhance reporting features

- src/pages/Report/OrderSheetSR/Thread.jsx
- src/pages/Report/OrderSheetSR/Zipper.jsx
Introduce a new column labeled 'Revise' in the order sheet to enhance data visibility and management.
> Add 'Revise' column to order sheet

- src/pages/Report/OrderSheetSR/Thread.jsx
- src/pages/Report/OrderSheetSR/Zipper.jsx
- src/pages/Report/ProductionSummary/ItemZipperEndWise.jsx
Introduce additional columns to enhance data representation in the table component. This change improves the overall usability and accessibility of the displayed information.
> Add more columns to the data table

- src/components/Pdf/OrderSheet/index.jsx
- src/components/Pdf/OrderSheet/utils.jsx
- src/components/Pdf/OrderSheetByStyle/index.jsx
- src/components/Pdf/OrderSheetByStyle/utils.jsx
- src/pages/Order/Details/ByOrderNumber/index.jsx
Update the order sheet PDF generation to include the current page number and total page count in the header. This change resolves an issue with the page number not displaying correctly.
> Fix page number display in order sheet PDF

- src/pages/Report/DailyChallan/index.jsx
- src/pages/Report/OrderStatusZipper/Zipper.jsx
Simplify data fetching in the DailyChallan and OrderStatusZipper components by removing an unused URL variable and streamlining the data handling logic.
> Refactor data fetching in components

- src/pages/Planning/ApprovalDate/index.jsx
- src/routes/private/Planning.jsx
- src/state/Planning.jsx
- src/state/QueryKeys.jsx
Introduce a new feature for managing planning approval dates, including a dedicated page and state management for bulk approval operations. This update enhances the planning module's functionality.
> Add Approval Date feature planning section

- src/components/Pdf/ZipperChallan/index.jsx
- src/pages/Delivery/Challan/index.jsx
- src/pages/Order/Details/Entry/index.jsx
- src/pages/Order/Details/Entry/spread-sheets/full-order.jsx
- src/pages/Order/Details/Entry/spread-sheets/tape.jsx
- src/pages/Order/Details/_components/Table/Column.jsx
- src/pages/Order/Details/_components/Table/index.jsx
- src/pages/Order/Details/_components/ViewByStyle/Column.jsx
- src/pages/Order/Details/_components/ViewByStyle/Table.jsx
- src/pages/Thread/Order/Details/Table/index.jsx
- src/pages/Thread/Order/Entry/index.jsx
- src/pages/Thread/Order/Entry/spreadsheets/order-entry-spreadsheet.jsx
- src/util/Schema/index.jsx
Introduce a new color reference field across various components and update the handling of color reference dates in the order entry process. Adjust table structures to accommodate the new field and ensure proper data flow for updates.
> Add color reference and update related functionalities

- src/pages/Thread/Order/index.jsx
Refactor the definition of the production pause column in the Order component for improved clarity and maintainability.
> Reorganize production pause column in Order component

- src/components/Pdf/OrderSheet/index.jsx
Enhance the color formatting to include a reference when available, improving clarity in the OrderSheetPdf component.
> Refactor color formatting in OrderSheetPdf component

- src/components/Pdf/ChallanStatusReport/index.jsx
- src/components/Pdf/ChallanStatusReport/zipper/index.jsx
- src/pages/Delivery/Challan/Entry/Header.jsx
- src/pages/Delivery/Challan/Entry/index.jsx
- src/pages/Delivery/Quantity-Return/Entry/Header.jsx
- src/pages/Delivery/Quantity-Return/Entry/columns.jsx
- src/pages/DyeingAndIron/ThreadBatch/index.jsx
- src/pages/DyeingAndIron/ZipperBatch/index.jsx
- src/pages/LabDip/Info/index.jsx
- src/pages/Order/Details/_components/Table/Column.jsx
- src/pages/Order/Details/_components/ViewByStyle/Column.jsx
- src/pages/Report/ApprovedOrders/Approved.jsx
- src/pages/Report/ApprovedOrders/partyWise.jsx
- src/pages/Report/PackingList/index.jsx
- src/pages/Report/ThreadBatch/index.jsx
- src/state/Other.jsx
- src/state/QueryKeys.jsx
Enhance the application by fixing various bugs and introducing a color reference feature to improve data handling and display. Adjustments made to data fetching and processing ensure better reliability and user experience.
> Implement bug fixes and add color reference feature

- src/pages/Report/IndividualMaterial/Header.jsx
- src/pages/Report/IndividualMaterial/index.jsx
- src/routes/private/Report.jsx
- src/state/QueryKeys.jsx
- src/state/Report.jsx
Introduce a new report for individual materials, including a dedicated header component and a table for displaying material details. Implement necessary hooks and routes to support the new report.
> Add Individual Materials report functionality

- src/pages/Metal/Finishing/Production/PolyTransfer.jsx
- src/pages/Nylon/MetallicFinishing/Production/PolyTransfer.jsx
- src/pages/Nylon/PlasticFinishing/Production/PolyTransfer.jsx
- src/pages/Vislon/Finishing/Production/PolyTransfer.jsx
Consolidate the default update object to improve code readability and maintainability. This change simplifies the component's initialization by using a single constant for the default values.
> Refactor default update object in PolyTransfer components

- src/pages/Delivery/PackingList/Entry/index.jsx
- src/pages/Store/Vendor/index.jsx
- src/pages/Store/VendorAccessories/index.jsx
- src/state/QueryKeys.jsx
- src/state/Store.jsx
Addressed issues related to URL handling in delivery packing list operations and refined the query parameters for the purchase vendor hook. Improved overall stability and performance.
> Fix bugs in delivery packing list and purchase vendor functionality

- src/pages/Report/ThreadProductionStatusOrderWise/index.jsx
Eliminate the date filter functionality from the ThreadProductionOW component to simplify data retrieval.
> Remove date filter from ThreadProductionOW

- src/pages/Report/DailyChallan/index.jsx
Clean up imports and enhance the Daily Challan report by adding a buyer name column for better data visibility.
> Refactor Daily Challan report and add buyer name column

- src/pages/Delivery/Challan/index.jsx
Introduce a new column for buyer names in the Delivery Challan table to enhance data visibility.
> Add buyer name column to Delivery Challan table

- src/pages/Order/Details/Entry/header/index.jsx
- src/pages/Order/Details/Entry/index.jsx
- src/pages/Order/Details/Entry/spread-sheets/full-order.jsx
- src/pages/Order/Details/Entry/spread-sheets/slider.jsx
- src/pages/Order/Details/Entry/spread-sheets/tape.jsx
- src/routes/private/Order.jsx
- src/state/Report.jsx
- src/ui/Dynamic/HandsonSpreadSheet/_actions/handle-actions.jsx
- src/ui/Dynamic/HandsonSpreadSheet/_actions/render-actions.jsx
- src/ui/Dynamic/HandsonSpreadSheet/test/index.jsx
Implement logic to prevent editing of order details if the planning quantity is greater than zero and the user lacks override access. This change enhances data integrity and user experience.
> Disable editing of order details based on planning quantity and access rights

- src/ui/Dynamic/HandsonSpreadSheet/_actions/handle-actions.jsx
Simplify the logic for checking batch quantity in the handleActions function to improve readability and maintainability.
> Refactor batch quantity check in handleActions function

- src/pages/Planning/ApprovalDate/index.jsx
Introduce a new 'Party' column in the Approval Date table to enhance data representation.
> Add 'Party' column to Approval Date table

- src/util/TransactionArea.jsx
Optimize the data processing module to enhance performance and reduce latency during execution. This includes refactoring code and implementing more efficient algorithms.
> Improve performance of data processing module

- src/components/Pdf/ThreadTravelCard/index.jsx
- src/components/Pdf/ThreadTravelCard/utils.jsx
Adjustments made to the PDF generation process to fix color discrepancies and update layout dimensions for better presentation.
> Fix PDF color issue and adjust layout dimensions

- src/pages/Planning/ApprovalDate/index.jsx
- src/pages/Report/ProductionStatement/index.jsx
- src/pages/Report/ProductionStatement/order/Excel/index.jsx
- src/pages/Report/ProductionStatement/production-v2/index.jsx
- src/pages/Report/ThreadProductionStatusOrderWise/index.jsx
Enhance the ApprovalDate table's column header, clean up unused imports, simplify total value calculations in the Excel report, and streamline state initialization in the production-v2 component. Additionally, improve JSX structure in the ThreadProductionStatusOrderWise component.
> Refactor various components for improved clarity and performance

- src/pages/Report/OrderStatusZipper/Zipper.jsx
Introduce new columns for bulk approval and bulk approval date in the order status report to enhance reporting capabilities.
> Add bulk approval and bulk approval date columns to order status report

- src/pages/Commercial/LC/Entry/index.jsx
Streamline the handling of LC entry data to enhance code readability and maintainability.
> Refactor LC entry data handling for improved readability

- src/pages/Maintenance/Issue/index.jsx
- src/pages/StoreMaintenance/Log/AgainstOrder/AddOrUpdate.jsx
- src/pages/StoreMaintenance/Log/AgainstOrder/Utils.js
- src/pages/StoreMaintenance/Log/AgainstOrder/index.jsx
- src/pages/StoreMaintenance/Stock/AgainstOrderTransfer.jsx
- src/pages/StoreMaintenance/Stock/MaterialTrx.jsx
- src/pages/StoreMaintenance/Stock/Utils.js
- src/pages/StoreMaintenance/Stock/index.jsx
- src/state/Other.jsx
- src/state/QueryKeys.jsx
- src/util/Schema/index.jsx
Addressed bugs related to maintenance stock handling and improved transaction logging for issues. Added new sections for better categorization and updated relevant schemas and components accordingly.
> Fix maintenance stock and transaction logging issues

- src/components/Pdf/DailyOrderStatus/index.jsx
Introduce a total calculation for each type in the Daily Order Status Report, enhancing the report's clarity and usability.
> Add type-wise total in Daily Order Status Report

- src/components/Pdf/DailyOrderStatus/index.jsx
Introduce functionality to calculate and display totals for each marketing category in the Daily Order Status report. This enhancement improves data visibility and reporting accuracy.
> Add marketing-wise total to Daily Order Status report

- src/pages/Delivery/PackingList-Bulk/Entry/index.jsx
- src/pages/Delivery/PackingList/Entry/index.jsx
- src/pages/Planning/ApprovalDate/index.jsx
- src/routes/private/Delivery.jsx
Improve access control mechanisms for packing lists by integrating new access checks and ensuring that only authorized users can perform certain actions.
> Enhance access control for packing lists and approval date

- src/components/Pdf/OrderSheet/index.jsx
- src/components/Pdf/OrderSheetByStyle/index.jsx
- src/components/Pdf/OrderSheetByStyle/utils.jsx
- src/components/Pdf/SliderDieCastingProduction/index.jsx
- src/pages/Admin/GlobalLog/index.jsx
- src/pages/Delivery/Challan/index.jsx
- src/pages/DyeingAndIron/ZipperBatch/index.jsx
- src/pages/Slider/DieCasting/Production/index.jsx
- src/routes/private/Hr.jsx
- src/state/Admin.jsx
- src/state/Other.jsx
- src/state/QueryKeys.jsx
- src/state/Slider.jsx
- src/ui/Others/TableExtraButtons/StatusSelect.jsx
Introduce filters for date range, order type, and product type across various components. Enhance the order sheet by adding new columns for weight and meter, and resolve a PDF generation error related to order details.
> Add filters and enhance order sheet functionality

- src/pages/Order/Details/ByOrderDescriptionUUID/index.jsx
- src/pages/Order/Details/ByOrderNumber/index.jsx
Correct the source references for the order sheet PDF to ensure the correct data is used for rendering and downloading.
> Fix order sheet PDF source references

- src/components/Pdf/DailyOrderStatus/index.jsx
Implement a grand total calculation for the marketing-wise table and display it in the Daily Order Status PDF.
> Add grand total calculation to Daily Order Status PDF

- src/components/ui/generate-pdf-button.jsx
- src/pages/Report/DailyProduction/index.jsx
- src/pages/Report/ProductionStatement/order-v2/index.jsx
- src/pages/Report/ProductionStatement/production-v2/index.jsx
Introduce a button to allow users to view the generated PDF directly in a new tab. This enhancement improves user experience by providing immediate access to the PDF without requiring a download.
> Add "View PDF" button to PdfGeneratorButton component

- src/pages/Maintenance/Issue/History.jsx
- src/pages/Maintenance/Issue/index.jsx
- src/pages/Report/PackingList/index.jsx
- src/ui/Others/DatePicker/index.jsx
Corrected the dateTime selection logic and added a filter for item types in the packing list report. Improved the handling of date selection and updated the status options accordingly.
> Fix dateTime selection and enhance packing list report

- src/components/Pdf/ProductionStatement/index.jsx
- src/components/Pdf/ProductionStatement/utils.jsx
- src/pages/Maintenance/Machine/AddOrUpdate.jsx
- src/pages/Maintenance/Machine/index.jsx
- src/pages/Report/ProductionStatement/production-v2/Excel/index.jsx
- src/pages/StoreMaintenance/Vendor/AddOrUpdate.jsx
- src/pages/StoreMaintenance/Vendor/index.jsx
Implement PDF generation using Web Workers for better performance, add various filters and columns to reports, and improve data handling and UI components across multiple modules. Fix several bugs related to notifications, PDF generation, and data validation.
> Enhance PDF generation and reporting features

- src/pages/Maintenance/Issue/AddOrUpdate.jsx
- src/pages/Maintenance/Issue/index.jsx
- src/pages/Order/Info/index.jsx
- src/pages/Order/Settings/index.jsx
- src/pages/Order/Settings/useHandle.js
- src/pages/Order/columns.jsx
- src/routes/private/Maintenance.jsx
- src/routes/private/Order.jsx
- src/routes/private/Report.jsx
- src/state/Maintenance.jsx
- src/state/Order.jsx
- src/state/QueryKeys.jsx
Introduce a new settings page that allows users to view their own orders and issues. Additionally, implement a toggle for canceling orders within the settings.
> Add settings page for showing own orders and issues

- src/pages/Commercial/LC/index.jsx
- src/pages/Report/LC/Header.jsx
- src/pages/Report/OrderStatusZipper/Zipper.jsx
Introduce new columns to display the names of the users who created and updated the entries in the Zipper report. This enhancement improves traceability and accountability within the report.
> Add 'Created By' and 'Updated By' columns in Zipper report

- src/pages/Accounting/CostCenter/AddOrUpdate.jsx
- src/pages/Accounting/CostCenter/config/schema/index.jsx
- src/pages/Accounting/CostCenter/index.jsx
- src/pages/Accounting/Ledger/AddOrUpdate.jsx
- src/pages/Accounting/Ledger/config/query/QueryKeys.jsx
- src/pages/Accounting/Ledger/config/query/index.jsx
- src/pages/Accounting/Ledger/config/schema/index.jsx
- src/pages/Accounting/Ledger/index.jsx
Introduce new fields for table selection in both cost-center and ledger forms, enhancing data management capabilities.
> Add table_name and table_uuid to cost-center and ledger forms

- src/pages/Report/DailyProduction/Excel/index.jsx
- src/pages/Report/DailyProduction/index.jsx
- src/pages/Report/ProductionStatement/production-v2/index.jsx
Eliminate unnecessary grand total calculations from the daily production report Excel export functionality to streamline the report generation process.
> Remove grand total calculations from daily production report Excel export

- src/pages/Report/OrderStatusThread/Thread.jsx
- src/pages/Report/OrderStatusZipper/Zipper.jsx
- src/pages/Report/ProductionSummary/ItemWise.jsx
- src/pages/Report/ProductionSummary/ItemZipperEndWise.jsx
- src/ui/Others/DatePicker/index.jsx
Adjust the time intervals in the date-time picker for improved usability.
> Fix date-time selection in zipper-batch dyeing report

- src/pages/Delivery/WarehouseRecv/index.jsx
Enhance the form layout by adding a new column for carton quantity in the entry table. This change improves data visibility and organization.
> Add carton quantity to entry table

- src/components/Pdf/ManualProformaInvoiceStyleWise/index.jsx
- src/components/Pdf/ManualProformaInvoiceStyleWise/utils.jsx
- src/pages/Commercial/ManualPI/Details/index.jsx
Introduce a new component for generating style-wise proforma invoices and enhance the PDF generation logic to support this new functionality.
> Add Manual Proforma Invoice Style Wise component and update PDF generation logic

- src/pages/DyeingAndIron/ZipperBatch/Details/Information.jsx
- src/pages/DyeingAndIron/ZipperBatch/index.jsx
- src/pages/Report/ZipperBatch/index.jsx
Improve the display of Yarn Issued information by adding units and formatting in the Information and Report components. Update the filter options to include Yarn Issued date.
> Enhance Information and Report components with Yarn Issued details and formatting

- src/pages/Report/OrderStatusZipper/Zipper.jsx
Improve cell rendering in the Zipper component and add a new column for total coloring quantity weight.
> Enhance Zipper component with improved rendering and new column

- src/pages/Report/OrderStatusZipper/Zipper.jsx
Simplify date handling logic and standardize column widths for better consistency in the Zipper component.
> Refactor date handling in Zipper component and adjust column widths

- src/pages/Report/utils.jsx
Enhance the user authentication process by streamlining login and registration, improving error handling, and adding validation checks. This update aims to provide a smoother user experience and increase security measures.
> Improve user authentication flow

- src/pages/Report/ZipperBatch/index.jsx
Update table column accessors to improve data handling and ensure accurate data representation in the UI.
> Refactor table column accessors for better data handling

- src/pages/Commercial/PI/index.jsx
Introduce an actions column in the PI table that allows users to edit and delete entries, enhancing user interaction and management capabilities.
> Add actions column with edit and delete functionality in PI table

- src/pages/Accounting/NeedToAccept/index.jsx
- src/pages/Accounting/Voucher/Entry/components/CostCenter.jsx
- src/pages/Accounting/Voucher/Entry/components/Header.jsx
- src/pages/Accounting/Voucher/Entry/components/VoucherEntryRow.jsx
- src/pages/Accounting/Voucher/Entry/hooks/useVoucherData.jsx
- src/pages/Accounting/Voucher/Entry/index.jsx
- src/pages/Accounting/Voucher/config/schema/index.jsx
- src/pages/Store/_components/Receive/Entry/Header.jsx
- src/routes/private/Acounting.jsx
- src/util/Schema/index.jsx
Integrate cost center selection and validate invoice numbers in the voucher entry process. This update improves data integrity and user experience during voucher creation.
> Enhance voucher entry with cost center and invoice validation

- src/components/Pdf/BalanceSheet/index.jsx
- src/pages/Accounting/Ledger/AddOrUpdate.jsx
- src/pages/Accounting/Ledger/index.jsx
- src/pages/Accounting/NeedToAccept/index.jsx
- src/pages/Accounting/Report/Accounting/index.jsx
- src/pages/Accounting/Report/config/query/QueryKeys.jsx
- src/pages/Accounting/Report/config/query/index.jsx
- src/pages/Accounting/Report/config/schema/index.jsx
- src/pages/Accounting/Voucher/Entry/components/CostCenter.jsx
- src/pages/Accounting/Voucher/Entry/components/CostCenterAdd.jsx
- src/pages/Accounting/Voucher/Entry/components/EmptyState.jsx
- src/pages/Accounting/Voucher/Entry/components/TableHead.jsx
- src/pages/Accounting/Voucher/Entry/components/VoucherEntryHeader.jsx
- src/pages/Accounting/Voucher/Entry/components/VoucherEntryRow.jsx
- src/pages/Accounting/Voucher/Entry/hooks/useNestedEntries.jsx
- src/pages/Accounting/Voucher/Entry/hooks/useVoucherSubmission.jsx
- src/pages/Accounting/Voucher/Entry/index.jsx
- src/pages/Accounting/Voucher/config/schema/index.jsx
- src/pages/Accounting/Voucher/utils.jsx
- src/routes/private/Acounting.jsx
Refactor components related to voucher entries for improved management and readability. Introduce new fields and hooks to enhance cost center handling and reporting functionality. Update schemas to accommodate nullable invoice numbers and add an initial amount field to the ledger schema.
> Refactor voucher entry components and enhance cost center handling

- src/components/ui/join-multi-input-buton.jsx
- src/pages/Maintenance/Machine/Utils.js
- src/pages/Order/OrderPricing/MarketingPriceForm.jsx
- src/pages/Order/OrderPricing/MdPriceForm.jsx
- src/pages/Order/OrderPricing/index.jsx
- src/pages/Store/_components/Log/AgainstOrder/Utils.js
- src/pages/Store/_components/Stock/Utils.js
- src/routes/private/Order.jsx
- src/state/Order.jsx
- src/state/QueryKeys.jsx
- src/util/Schema/index.jsx
Introduce forms for handling Marketing and MD pricing with multi-input capabilities. Add a maintenance comment in Utils.js for improved clarity.
> Add Marketing and MD Price forms with maintenance comment
