src/pages/Admin/User/AddOrUpdate.jsx, src/pages/Admin/User/index.jsx, src/state/Admin/QueryKeys.jsx, src/state/Admin/user.jsx, src/state/index.jsx
The code changes include adding query keys for users and buyers in the admin section. This will allow for more efficient querying and retrieval of data related to users and buyers. The changes also include updating the printWidth in the prettierrc file and removing unused files. Additionally, there are updates to the nanoid generation in the nanoid.jsx and buyer.jsx files.
Please note that the recent user commits and repository commits are not directly related to the code changes mentioned above.
=> feat: Add admin query keys for users and buyers

src/pages/Order/Merchandiser/AddOrUpdate.jsx, src/util/GetDateTime.jsx
This pull request updates the `GetDateTime` function to use a 24-hour time format instead of the previous format. The function now returns the date and time in the format "yyyy-MM-dd HH:mm:ss". This change ensures consistency in the date and time formatting throughout the codebase.
=> Update GetDateTime format to use 24-hour time

src/pages/Commercial/Cash/Entry/index.jsx
This pull request adds the conversion rate and receive amount fields to the cash entry form in the Commercial Cash module. These fields allow users to enter the conversion rate and the amount received for a cash transaction. The changes include updating the form component to include the new fields and updating the API endpoint for updating cash transactions. This pull request addresses issues #174 and #173.
=> Add conversion rate and receive amount fields to cash entry form

src/pages/Common/Transfer/EntryUpdate/index.jsx
Eliminate unused commented-out code related to `sfg_uuid` and `trx_quantity_in_meter` for the Tape In dyed store entry to improve code clarity.
=> Refactor: Remove commented-out code for Tape In dyed store entry

src/components/Pdf/OrderSheet/utils.jsx, src/components/Pdf/OrderSheet2/utils.jsx
Update the lock_type_name in the TableHeader component for OrderSheet to reflect the correct type as Slider instead of Tape.
=> Change lock_type_name from Tape to Slider in TableHeader

src/components/Pdf/ProformaInvoice/utils.jsx, src/pages/Commercial/Bank/AddOrUpdate.jsx, src/pages/Commercial/Bank/index.jsx, src/util/Schema/index.jsx
Introduce an account number field and update bank details, including BIN and VAT information, in the Proforma Invoice.
=> feat:Add account number and tax information to Proforma Invoice

src/components/Pdf/ProformaInvoice/index.jsx
Correct the calculation of total values for thread orders and introduce a grand total display for both thread and zipper orders.
=> Fix total value calculation and add grand total display for orders

src/pages/Thread/Order/index.jsx
Update the default status from 'bulk' to 'all' in the Order component for improved clarity and usability.
=> Change default status in Order component to 'all'

src/components/Pdf/ZipperChallan/index.jsx
Introduce a display for poly quantity associated with packing numbers in the Zipper Challan PDF.
=> fix:Add poly quantity display for packing numbers in Zipper Challan PDF

src/components/Pdf/ThreadTravelCard/index.jsx
Ensure the expected weight is displayed with three decimal places in the Thread Travel Card PDF.
=> Format expected weight to three decimal places in Thread Travel Card PDF

src/components/Pdf/DailyProduction/index.jsx
Exclude certain sizes from the grand total calculations in the DailyProduction PDF to ensure accurate reporting.
=> Exclude specific sizes from grand total calculations in DailyProduction PDF

src/pages/DyeingAndIron/ZipperBatch/Entry/index.jsx
Modify the calculation of itemTotal to default to 0 when no value is returned from getRequiredTapeKg. This change improves the robustness of the tape order calculation.
=> Ensure itemTotal defaults to 0 in tape calculation

src/components/Pdf/ThreadBulkRecipe/index.jsx
Adjust the bulk precision in the PDF recipe component to three decimal places for improved accuracy.
=> Update bulk precision to 3 decimal places in PDF recipe component

src/components/Pdf/DailyProduction/index.jsx
Add a condition to ensure that the 'Order Wise Total' entry does not get duplicated in the DailyProduction PDF.
=> Prevent duplicate 'Order Wise Total' entry in DailyProduction PDF

src/pages/Report/ProductionStatement/Header.jsx, src/pages/Report/ProductionStatement/index.jsx, src/state/QueryKeys.jsx, src/state/Report.jsx
Introduce a report selection feature in the ProductionStatement header, allowing users to choose between different report types. This enhances the filtering capabilities of the report generation process.
=> Add report selection functionality in ProductionStatement header

src/components/Pdf/ProformaInvoice/index.jsx
Adjust table widths for better layout and implement a total calculation for thread and zipper orders.
=> Update ProformaInvoice table widths and add total calculation for orders

src/components/Pdf/ManualProformaInvoice/utils.jsx, src/components/Pdf/ProformaInvoice/utils.jsx, src/components/Pdf/utils.jsx
Revise company details in PDF headers to include the company name, BIN, and tax information, while correcting the company name to "Fortune Zipper Limited."
=> Update company information in PDF headers

src/components/Pdf/ProformaInvoice/index.jsx, src/components/Pdf/ProformaInvoice/utils.jsx, src/pages/Commercial/PI/Details/Information.jsx, src/pages/Commercial/PI/Entry/Header.jsx
Introduce gross weight and cross weight fields to the details page, enhancing the information displayed for better clarity. Adjustments made to the layout and labels for improved presentation.
=> Add gross weight to details page

src/pages/Slider/Dashboard/index.jsx
Update the balance calculation to utilize `batch_quantity` instead of `swatch_approved_quantity` for improved accuracy.
=> Refactor balance calculation to use batch quantity

src/pages/Report/DeliveryReport/Thread.jsx, src/pages/Report/DeliveryReport/Zipper.jsx
Introduce a new 'Unit' column in delivery reports and update existing headers for better clarity.
=> Add 'Unit' column and improve header clarity in delivery reports

src/pages/Report/OrderStatus/Thread.jsx, src/pages/Report/OrderStatus/Zipper.jsx, src/routes/private/Report.jsx
Introduce price columns for party and company in order status reports, displaying them based on user access permissions.
=> Add price columns to order status reports with conditional visibility

src/pages/Report/ThreadDelivery/index.jsx, src/routes/private/Report.jsx, src/state/QueryKeys.jsx, src/state/Report.jsx
Introduce a new report for Thread Delivery, including a dedicated page and hooks for data fetching. Update routing to include the new report and ensure proper access controls.
=> Add Thread Delivery report feature

src/pages/Commercial/PI/Details/index.jsx
Introduce a new flex container to improve the layout of iframe elements on the PI details page.
=> Add a flex container for iframe elements in PI details page

src/pages/Commercial/LC/Details/Information.jsx, src/pages/Commercial/LC/Entry/Header.jsx, src/util/Schema/index.jsx
Update the handling of export LC dates and modify the schema to allow nullable fields for certain date properties. This change improves data flexibility and aligns with the updated requirements.
=> Refactor export LC date handling and update schema for nullable fields

src/pages/Order/Details/Entry/index.jsx, src/pages/Order/Details/_components/Table/Column.jsx, src/pages/Order/Details/_components/Table/History.jsx, src/pages/Order/Details/_components/Table/index.jsx
Resolve an issue where the history was not displayed correctly in order details. The changes ensure that the created_by field is populated and that the history is conditionally rendered.
=> Fix History bug in order details

src/components/Pdf/OrderSheetByStyle/index.jsx
Resolve an issue with the calculation of rowSpan in the order PDF, ensuring accurate rendering of details.
=> Fix order PDF 2 bug

src/pages/Commercial/Cash/index.jsx
Ensure that the cash value displays as 0 instead of undefined when no value is present.
=> Fix cash bug in data display

src/pages/Report/ProductionStatement/order/Header.jsx, src/pages/Report/ProductionStatement/production/Header.jsx
Implement a user-specific path for fetching parties in production statement headers based on user access rights. This change enhances data retrieval by ensuring users only access their own orders when applicable.
=> Integrate user-specific path for fetching parties in production statements

src/pages/Dashboard/_components/BarChartOverall/index.jsx
Enhance the tooltip in the Order Received chart to display additional values for different materials, including Metal, Nylon, N-Plastic, and Vislon. This improves data visibility and user understanding of the chart.
=> Add tooltip for Order Received chart with extra values

src/pages/Delivery/PackingList/index.jsx
Implement carton quantity calculation based on item type in the packing list, allowing for accurate representation of quantities for different item types.
=> Add carton quantity calculation to packing list

src/pages/Dashboard/_components/BarChartOverall/index.jsx, src/pages/Dashboard/hooks/useDashboardData.js, src/pages/Dashboard/index.jsx, src/pages/Dashboard/query/index.js, src/pages/Dashboard/query/queryKeys.js
Introduce a day range selector for the order received chart, allowing users to filter data by the last 30 days or the last 12 months. Update the dashboard data fetching to accommodate the selected date range.
=> Add day range selection for dashboard order received

src/pages/Report/OrderSummary/TransposedTable.jsx
Correct the URL used for linking to order details to ensure it references the correct order number.
=> Fix URL construction for order details

src/components/Pdf/PackingListSticker/index.jsx
Introduce a display for the packing number on the packing list sticker to enhance visibility and information provided.
=> Add packing number display to packing list sticker

src/components/Pdf/ManualProformaInvoice/utils.jsx
Update the proforma invoice header to display the party name instead of the factory name.
=> Correct factory name to party name in proforma invoice header

src/components/Pdf/ManualProformaInvoice/index.jsx, src/components/Pdf/ThreadPackeListStickerV2/index.jsx
Update the row filtering logic to use the correct property for order number in thread data. This change ensures accurate filtering based on the intended property.
=> Fix row filtering logic for order number in thread data

src/pages/LabDip/Recipe/index.jsx, src/state/LabDip.jsx, src/state/QueryKeys.jsx
Introduce a status filter for lab dip recipes, allowing users to filter by different recipe types. Update the related hooks and query keys to accommodate the new filtering feature.
=> Add lab/recipe filter functionality

src/pages/LabDip/ThreadSwatch/index.jsx, src/pages/LabDip/ZipperSwatch/index.jsx
Introduce a new order filter for lab-dip zipper and thread components, allowing users to select between complete and incomplete orders. This enhances the filtering capabilities of the application.
=> Add new order filter for lab-dip zipper and thread

src/pages/Delivery/Log/WarehouseNotOut/index.jsx, src/pages/Delivery/Log/WarehouseOut/index.jsx, src/pages/Delivery/Log/WarehouseRCV/index.jsx, src/state/Store.jsx
Introduce a new 'Sample' column in the WarehouseNotOut and WarehouseRCV logs, utilizing the StatusButton component for better visual representation of sample status.
=> Add 'Sample' column with StatusButton in Warehouse logs

src/pages/Delivery/PackingList/Entry/index.jsx, src/pages/Order/Details/ByOrderDescriptionUUID/index.jsx, src/pages/Order/Details/_components/Table/index.jsx
Implement finishing balance calculation and display it in the order details table. Additionally, handle cases where the packing list is already received to prevent further updates.
=> Add finishing balance calculation and display in order details

src/components/Pdf/OrderSheet/utils.jsx, src/components/Pdf/OrderSheetByStyle/utils.jsx, src/pages/Commercial/PI/index.jsx
Introduce an O/N column to display order numbers along with delivery and packing list percentages in a tabular format on the Index page. This enhances the visibility of order-related metrics.
=> Add O/N column delivery and packing list percentage to Index page

src/components/Pdf/OrderSheet/utils.jsx, src/components/Pdf/OrderSheetByStyle/utils.jsx
Update the date reference in the getPageHeader function to use `order_description_created_at` instead of `order_description_updated_at`. This change ensures the correct date is displayed.
=> Fix date reference in getPageHeader function

src/pages/Commercial/PI/index.jsx
Optional chaining has been implemented to enhance error handling when accessing properties of order objects, ensuring that the application does not crash due to undefined values.
=> Add optional chaining to prevent errors accessing order properties

src/pages/Delivery/Log/WarehouseNotOut/index.jsx, src/pages/Delivery/Log/WarehouseOut/index.jsx, src/pages/Delivery/Log/WarehouseRCV/index.jsx, src/state/Delivery.jsx, src/state/QueryKeys.jsx
Introduce a status selection feature for filtering delivery logs by sample or bulk. Update relevant hooks and query keys to accommodate the new filtering option.
=> Add sample/bulk filter to delivery logs

src/pages/Order/Details/Entry/index.jsx, src/pages/Thread/Order/Entry/index.jsx
Ensure that the postData mutation handles cases where newEntry and newOrder are empty, preventing unnecessary requests.
=> Handle empty newEntry and newOrder cases in postData mutation

src/pages/Report/OrderStatus/Zipper.jsx, src/pages/Report/utils.jsx
Introduce a new utility for time formatting and update the date display in the OrderStatus table to include time. This enhances the clarity of date information presented to users.
=> Add time formatting utility and update date display in OrderStatus table

src/pages/Report/OrderStatus/Thread.jsx, src/pages/Report/OrderStatus/Zipper.jsx
Correct the mapping of LC numbers in the Thread and Zipper components to ensure accurate data display. This change enhances the representation of LC numbers in the user interface.
=> Fix LC number mapping in Thread and Zipper components

src/pages/Report/OrderStatusThread/Thread.jsx
Introduce a new column for 'Warehouse QTY' in the Order Status table and remove an unused URL from the useThreadStatus hook.
=> Add 'Warehouse QTY' column to Order Status table and clean up useThreadStatus hook

src/components/Pdf/OrderSheet/index.jsx, src/components/Pdf/ThreadOrderSheet/index.jsx, src/pages/LabDip/ThreadSwatch/index.jsx, src/pages/LabDip/ZipperSwatch/index.jsx, src/pages/Thread/Order/Details/index.jsx, src/util/Schema/index.jsx
Enhance the order sheet PDF and labdip components by incorporating the color_ref attribute, improving the representation of color information in the output.
=> Add color_ref to PDF and labdip exports

src/pages/DyeingAndIron/ThreadBatch/index.jsx, src/pages/DyeingAndIron/ZipperBatch/index.jsx, src/pages/LabDip/Info/index.jsx, src/pages/LabDip/ThreadSwatch/index.jsx, src/pages/LabDip/ZipperSwatch/index.jsx, src/pages/Planning/ApprovalDate/index.jsx, src/pages/Planning/Overview/index.jsx, src/pages/Report/Bulk/index.jsx, src/pages/Report/DeliveryReport/Thread.jsx, src/pages/Report/DeliveryReport/Zipper.jsx, src/pages/Report/OrderTracking/index.jsx, src/pages/Report/PackingList/index.jsx, src/pages/Report/Sample/index.jsx, src/pages/Report/ThreadBatch/index.jsx, src/pages/Report/ThreadProductionStatus/thread-production.jsx, src/pages/Report/ThreadProductionStatusOrderWise/index.jsx, src/state/Report.jsx
Update the query parameters in the daily challan report to use `from_date` and `to_date` for consistency.
=> Fix date parameter naming in daily challan report query

src/pages/Delivery/Challan/index.jsx
Revise the delivery permission check to utilize 'is_out_for_delivery' instead of 'gate_pass' for improved accuracy.
=> Update delivery permission check logic

src/pages/Order/columns.jsx
Corrected the spelling of 'cancelled' in the InfoColumns component to ensure consistency and accuracy.
=> Fix spelling of 'cancelled' in InfoColumns

src/pages/DyeingAndIron/ThreadBatch/Details/Table.jsx, src/pages/Thread/Order/Details/Table/index.jsx
Introduce a new 'Damaged' column in both the ThreadBatch and Order details tables to track damaged quantities.
=> Add 'Damaged' column to ThreadBatch and Order details tables

src/pages/Commercial/Cash/index.jsx, src/pages/Planning/ApprovalDate/index.jsx
Implement optional chaining to prevent errors when accessing order and thread number mappings, enhancing the robustness of the code.
=> Add optional chaining for safer order and thread mappings

src/pages/Planning/ApprovalDate/index.jsx
Show the name of the user who initiated the bulk approval in the approval date section for better clarity.
=> Display bulk approval name in the approval date section

src/pages/DyeingAndIron/ZipperBatch/index.jsx
Resolve an issue with the item_descriptions field by modifying the accessor function to correctly format the item descriptions for display.
=> Fix item_descriptions bug in zipper/batch processing

src/pages/Report/ZipperBatch/index.jsx, src/routes/private/Report.jsx
Update all references in routing and components to reflect the new name, ensuring consistency throughout the application.
=> Rename Zipper Batch to Zipper Dyeing Batch

src/pages/Report/ZipperBatch/index.jsx
Introduce filter type options to enhance the Zipper Dyeing Batch report functionality, allowing users to filter by dyeing status and stock received dates.
=> Add filter type options for Zipper Dyeing Batch report

src/util/Schema/index.jsx
Update the DYEING_BATCH_PRODUCTION_SCHEMA to enforce that the yarn issued is a double, ensuring more precise data handling.
=> Require double for yarn issued in production schema

src/pages/DyeingAndIron/ZipperBatch/Production/index.jsx
Remove the disabled state from the button to allow interaction regardless of the update state, and streamline form attributes for better clarity.
=> Enable button regardless of update state and clean up form attributes

src/pages/DyeingAndIron/ZipperBatch/Production/index.jsx, src/pages/LabDip/ZipperSwatch/index.jsx, src/state/Dyeing.jsx
Fetch operations for dyeing batch details now occur only when a valid UUID is provided, optimizing data retrieval and preventing unnecessary requests.
=> Enable fetching dyeing batch details conditionally by UUID

src/pages/DyeingAndIron/ZipperBatch/Production/Header.jsx, src/pages/DyeingAndIron/ZipperBatch/Production/index.jsx, src/pages/LabDip/ThreadSwatch/index.jsx, src/pages/LabDip/ZipperSwatch/index.jsx
Enhance data submissions in the LabDip and ZipperSwatch components by including `updated_at` and `updated_by` fields for better tracking of changes. Additionally, streamline the remarks field handling.
=> Add updated_at and updated_by fields to LabDip and ZipperSwatch submissions
